Repository IBM/ibm-licensing-operator, pull requests merged in 2020-11, with the labels that each got.

#181 Dev channel update
  deploy/olm-catalog/ibm-licensing-operator/ibm-licensing-operator.package.yaml
Labels: approved, lgtm, size/XS

#182 Add some features to automatic script
  common/scripts/ibm_licensing_operator_install.sh
Labels: approved, lgtm, size/M

#183 Bk installationwithout olm
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
  docs/Content/Installation_scenarios.md
  docs/Content/Preparing_for_installation.md
  docs/License_Service_main.md
Labels: approved, lgtm, size/L

#184 Recent updates
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
Labels: approved, lgtm, size/S

#185 update ubi image to 8.3-201
  build/Dockerfile
Labels: approved, lgtm, size/XS

#186 update operand sha to latest 1.3.0 versions
  deploy/olm-catalog/ibm-licensing-operator/1.3.0/ibm-licensing-operator.v1.3.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/apis/operator/v1alpha1/helper.go
Labels: approved, lgtm, size/S

#187 update ui operand digest
  deploy/olm-catalog/ibm-licensing-operator/1.3.0/ibm-licensing-operator.v1.3.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/apis/operator/v1alpha1/helper.go
Labels: approved, lgtm, size/XS

#188 fix-offline-install
  deploy/olm-catalog/ibm-licensing-operator/1.3.0/ibm-licensing-operator.v1.3.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#189 update all versions according to 1.3.1 versions
  .github/workflows/kind.yml
  Makefile
  common/scripts/tests/.osdk-scorecard.yaml
  common/scripts/tests/tests.bats
  common/scripts/tests/tests_reporter.bats
  deploy/crds/operator.ibm.com_v1alpha1_ibmlicenseservicereporter_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_ibmlicensing_cr.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.3.1/ibm-licensing-operator.v1.3.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.3.1/operator.ibm.com_ibmlicenseservicereporters_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.3.1/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/ibm-licensing-operator.package.yaml
  deploy/operator.yaml
  pkg/apis/operator/v1alpha1/helper.go
  version/version.go
Labels: approved, lgtm, size/XXL

#190 update documentation to address found issues
  README.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
  docs/Content/Preparing_for_installation.md
  docs/Content/Troubleshooting.md
  docs/Content/Uninstalling.md
Labels: approved, lgtm, size/M

#191 updated ls operand digest
  deploy/olm-catalog/ibm-licensing-operator/1.3.1/ibm-licensing-operator.v1.3.1.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/apis/operator/v1alpha1/helper.go
Labels: approved, lgtm, size/S

#192 Update ui operand digest
  deploy/olm-catalog/ibm-licensing-operator/1.3.1/ibm-licensing-operator.v1.3.1.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/apis/operator/v1alpha1/helper.go
Labels: approved, lgtm, size/XS

#196 Digest Update 1605776381
  deploy/olm-catalog/ibm-licensing-operator/1.3.1/ibm-licensing-operator.v1.3.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#199 Prepare release-4.0 branch
  .github/workflows/kind.yml
  common/scripts/tests/.osdk-scorecard.yaml
  common/scripts/tests/tests_reporter.bats
  deploy/crds/operator.ibm.com_v1alpha1_ibmlicenseservicereporter_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_ibmlicensing_cr.yaml
Labels: approved, lgtm, size/S

#202 Digest Update 1606317737
  deploy/olm-catalog/ibm-licensing-operator/1.3.1/ibm-licensing-operator.v1.3.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#205 Digest Update 1606503767
  deploy/olm-catalog/ibm-licensing-operator/1.3.1/ibm-licensing-operator.v1.3.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/XS

#206 changed receiver mem limit
  pkg/apis/operator/v1alpha1/helper.go
Labels: approved, lgtm, size/XS
