Repository IBM/ibm-licensing-operator, pull requests merged in 2020-05, with the labels that each got.

#35 fix IBM Licensing Service into IBM License Service
  README.md
Labels: approved, lgtm, size/XS

#36 update base ubi image to 8.2-267
  build/Dockerfile
Labels: approved, lgtm, size/XS

#39 Add automatic scripts
  Makefile
  README.md
  common/scripts/ibm_licensing_operator_install.sh
  common/scripts/push-csv.sh
Labels: approved, lgtm, size/XL

#37 fix for cv certification
  Makefile
  README.md
  common/Makefile.common.mk
  common/scripts/.githooks/make_lint-all.sh
  deploy/crds/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_ibmlicensing_cr.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.1.0/ibm-licensing-operator.v1.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.1.0/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/ibm-licensing-operator.package.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  go.mod
  go.sum
  pkg/apis/operator/v1alpha1/ibmlicensing_types.go
Labels: approved, lgtm, size/L

#40 Add upload token
  common/Makefile.common.mk
  deploy/crds/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.1.0/ibm-licensing-operator.v1.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.1.0/operator.ibm.com_ibmlicensings_crd.yaml
  pkg/apis/operator/v1alpha1/ibmlicensing_types.go
  pkg/controller/ibmlicensing/ibmlicensing_controller.go
  pkg/resources/secrets.go
  pkg/resources/volumes.go
Labels: approved, lgtm, size/L

#42 Add digest support
  Makefile
  README.md
  common/scripts/get-image-sha.sh
  deploy/crds/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_ibmlicensing_cr.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.1.0/ibm-licensing-operator.v1.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.1.0/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/operator.yaml
  images/IBMLicensingOperatorParameters.csv
  pkg/apis/operator/v1alpha1/helper.go
  pkg/apis/operator/v1alpha1/ibmlicensing_types.go
Labels: approved, lgtm, size/L

#41 Fix automatic script for icp
  README.md
  common/scripts/ibm_licensing_operator_install.sh
Labels: approved, lgtm, size/L

#43 Add digest to operator.yaml and csv yaml
  common/scripts/get-image-sha.sh
  deploy/olm-catalog/ibm-licensing-operator/1.1.0/ibm-licensing-operator.v1.1.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#44 update product version in annotations
  README.md
  deploy/crds/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.1.0/ibm-licensing-operator.v1.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.1.0/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/operator.yaml
  pkg/resources/helper.go
Labels: approved, lgtm, size/S

#45 Bk new readme template
  README.md
Labels: approved, lgtm, size/M

#46 potential fix for invalid CRD on OCP 4.4
  deploy/crds/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.1.0/operator.ibm.com_ibmlicensings_crd.yaml
  pkg/apis/operator/v1alpha1/ibmlicensing_types.go
Labels: approved, lgtm, size/XS

#47 add big description for csv
  deploy/olm-catalog/ibm-licensing-operator/1.1.0/ibm-licensing-operator.v1.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#48 add overriding image possibility, CR > ENV > default values
  deploy/crds/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.1.0/operator.ibm.com_ibmlicensings_crd.yaml
  pkg/apis/operator/v1alpha1/helper.go
  pkg/apis/operator/v1alpha1/ibmlicensing_types.go
  pkg/controller/ibmlicensing/ibmlicensing_controller.go
Labels: approved, lgtm, size/L

#49 Use digest to replace tag and Create beta channel
  deploy/olm-catalog/ibm-licensing-operator/1.1.0/ibm-licensing-operator.v1.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-licensing-operator/ibm-licensing-operator.package.yaml
Labels: approved, lgtm, size/XS

#50 update dev version to 1.1.1, add operand version to CR
  deploy/crds/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_ibmlicensing_cr.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.1.1/ibm-licensing-operator.v1.1.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.1.1/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/ibm-licensing-operator.package.yaml
  deploy/operator.yaml
  pkg/apis/operator/v1alpha1/helper.go
  pkg/apis/operator/v1alpha1/ibmlicensing_types.go
  pkg/controller/ibmlicensing/ibmlicensing_controller.go
  version/version.go
Labels: approved, lgtm, size/M

#52 update operator tag in dev csv for new version 1.1.1
  deploy/olm-catalog/ibm-licensing-operator/1.1.1/ibm-licensing-operator.v1.1.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#53 add missing csv 1.1.0
  deploy/olm-catalog/ibm-licensing-operator/1.1.0/ibm-licensing-operator.v1.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.1.0/operator.ibm.com_ibmlicensings_crd.yaml
Labels: approved, lgtm, size/XXL

#54 fix 1.1.1 CRD to not force version parameter that breaks backward
  deploy/crds/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.1.1/operator.ibm.com_ibmlicensings_crd.yaml
  pkg/apis/operator/v1alpha1/ibmlicensing_types.go
Labels: approved, lgtm, size/XS

#55 update beta csv to 1.1.1 also include newest operator digest
  deploy/olm-catalog/ibm-licensing-operator/1.1.1/ibm-licensing-operator.v1.1.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-licensing-operator/ibm-licensing-operator.package.yaml
Labels: approved, lgtm, size/XS

#57 update operand to 1.1.2 and add new dev operator version
  deploy/crds/operator.ibm.com_v1alpha1_ibmlicensing_cr.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.1.2/ibm-licensing-operator.v1.1.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.1.2/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/ibm-licensing-operator.package.yaml
  deploy/operator.yaml
  pkg/apis/operator/v1alpha1/helper.go
  version/version.go
Labels: approved, lgtm, size/XXL

#58 update 1.1.2 to beta
  deploy/olm-catalog/ibm-licensing-operator/1.1.2/ibm-licensing-operator.v1.1.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-licensing-operator/ibm-licensing-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS
