Repository IBM/ibm-licensing-operator, pull requests merged in 2020-12, with the labels that each got.

#214 update to use newer version from stable
  README.md
  deploy/olm-catalog/ibm-licensing-operator/ibm-licensing-operator.package.yaml
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
  docs/Content/Troubleshooting.md
  docs/Content/Uninstalling.md
Labels: approved, lgtm, size/M

#215 cleanup before merging into master
  common/scripts/catalog_build.sh
  deploy/crds/operator.ibm.com_v1alpha1_ibmlicensing_cr.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.3.1/ibm-licensing-operator.v1.3.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-licensing-operator/ibm-licensing-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#216 Release 1.4
  .github/workflows/kind.yml
  Makefile
  common/scripts/tests/.osdk-scorecard.yaml
  common/scripts/tests/tests.bats
  common/scripts/tests/tests_reporter.bats
  deploy/crds/operator.ibm.com_v1alpha1_ibmlicenseservicereporter_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_ibmlicensing_cr.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/ibm-licensing-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/operator.ibm.com_ibmlicenseservicereporters_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/ibm-licensing-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/XXL

#208 remove digest from operator
  cmd/manager/main.go
  common/scripts/tests/tests.bats
  common/scripts/tests/tests_reporter.bats
  docs/Content/Troubleshooting.md
  pkg/apis/operator/v1alpha1/helper.go
  pkg/controller/ibmlicenseservicereporter/ibmlicenseservicereporter_controller.go
  pkg/controller/ibmlicensing/ibmlicensing_controller.go
  pkg/resources/helper.go
Labels: approved, lgtm, size/L

#213 Improve linting experience
  CONTRIBUTING.md
  Makefile
  common/Makefile.common.mk
  common/config/sass-lint.yml
  common/config/tslint.json
Labels: approved, lgtm, size/L

#223 Digest Update 1607681936
  deploy/olm-catalog/ibm-licensing-operator/1.3.2/ibm-licensing-operator.v1.3.2.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#224 Digest Update 1607683126
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/ibm-licensing-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#225 Building catalog with version tags
  common/scripts/catalog_build.sh
Labels: approved, lgtm, size/XS

#226 Building catalog with version tags
  common/scripts/catalog_build.sh
Labels: approved, lgtm, size/XS

#222 update licensing information
  LICENSE
Labels: approved, lgtm, size/S

#231 Digest Update 1607982936
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/ibm-licensing-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#232 Digest Update 1608039766
  deploy/olm-catalog/ibm-licensing-operator/1.3.2/ibm-licensing-operator.v1.3.2.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#198 Rhmp
  cmd/manager/main.go
  common/scripts/tests/tests_reporter.bats
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/ibm-licensing-operator.v1.4.0.clusterserviceversion.yaml
  deploy/role.yaml
  go.mod
  go.sum
  pkg/apis/operator/v1alpha1/helper.go
  pkg/apis/operator/v1alpha1/ibmlicensing_types.go
  pkg/controller/ibmlicensing/ibmlicensing_controller.go
  pkg/resources/helper.go
  pkg/resources/service/containers.go
  pkg/resources/service/helper.go
  pkg/resources/service/networking.go
  pkg/resources/service/service_monitor.go
  pkg/resources/service/services.go
Labels: approved, lgtm, size/XXL

#233 added rhmp param to crd
  deploy/crds/operator.ibm.com_ibmlicensings_crd.yaml
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XS

#241 unitest based on ginkgo, gomega and testEnv
  .github/workflows/kind.yml
  Makefile
  common/scripts/codecov.sh
  controllers/ibmlicensing_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#243 rhmp bug fixes and enhancements
  controllers/ibmlicensing_controller.go
  controllers/resources/service/helper.go
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/ibm-licensing-operator.v1.4.0.clusterserviceversion.yaml
  deploy/role.yaml
  main.go
Labels: approved, lgtm, size/M

#244 fix coverage
  .github/workflows/kind.yml
  Makefile
Labels: approved, lgtm, size/S

#250 Digest Update 1609192535
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/ibm-licensing-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S
