Repository IBM/ibm-licensing-operator, pull requests merged in 2020-09, with the labels that each got.

#109 Add OCP Cert Manager
  deploy/crds/operator.ibm.com_ibmlicenseservicereporters_crd.yaml
  deploy/crds/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.2.0/operator.ibm.com_ibmlicenseservicereporters_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.2.0/operator.ibm.com_ibmlicensings_crd.yaml
  pkg/apis/operator/v1alpha1/helper.go
  pkg/controller/ibmlicenseservicereporter/ibmlicenseservicereporter_controller.go
  pkg/controller/ibmlicensing/ibmlicensing_controller.go
  pkg/resources/helper.go
  pkg/resources/reporter/helper.go
  pkg/resources/reporter/services.go
  pkg/resources/service/helper.go
  pkg/resources/service/services.go
Labels: approved, lgtm, size/L

#108 change ui path name
  deploy/olm-catalog/ibm-licensing-operator/1.2.0/ibm-licensing-operator.v1.2.0.clusterserviceversion.yaml
  pkg/apis/operator/v1alpha1/helper.go
  pkg/resources/reporter/routing.go
Labels: approved, lgtm, size/S

#113 fix readiness probe trying wrong path
  pkg/resources/reporter/ui.go
Labels: approved, lgtm, size/XS

#115 fix deployment reconcilation
  pkg/controller/ibmlicenseservicereporter/ibmlicenseservicereporter_controller.go
  pkg/controller/ibmlicensing/ibmlicensing_controller.go
  pkg/resources/deployments.go
Labels: approved, lgtm, size/L

#114 Remove Cluster SA and Role from Operator and move to OLM
  deploy/olm-catalog/ibm-licensing-operator/1.2.0/ibm-licensing-operator.v1.2.0.clusterserviceversion.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  pkg/controller/ibmlicensing/ibmlicensing_controller.go
  pkg/resources/service/deployments.go
  pkg/resources/service/helper.go
  pkg/resources/service/rbac.go
Labels: approved, lgtm, size/XL

#117 fix probe nil pointer error
  pkg/resources/deployments.go
Labels: approved, lgtm, size/XS

#116 Remove Cluster SA i Role from Operator and move to OLM
  deploy/olm-catalog/ibm-licensing-operator/1.2.0/ibm-licensing-operator.v1.2.0.clusterserviceversion.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
Labels: approved, lgtm, size/L

#118 Remove metering dependency
  deploy/crds/operator.ibm.com_v1alpha1_ibmlicensing_cr.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.2.0/ibm-licensing-operator.v1.2.0.clusterserviceversion.yaml
  images/IBMLicensingOperatorParameters.csv
  pkg/controller/ibmlicenseservicereporter/ibmlicenseservicereporter_controller.go
  pkg/resources/helper.go
Labels: approved, lgtm, size/M

#119 add arch support labels to csv
  deploy/olm-catalog/ibm-licensing-operator/1.2.0/ibm-licensing-operator.v1.2.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#120 update version to 1.2.1 for operator only
  deploy/olm-catalog/ibm-licensing-operator/1.2.1/ibm-licensing-operator.v1.2.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.2.1/operator.ibm.com_ibmlicenseservicereporters_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.2.1/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/ibm-licensing-operator.package.yaml
  version/version.go
Labels: approved, lgtm, size/XXL

#121 update to latest ubi base in Dockerfile
  build/Dockerfile
Labels: approved, lgtm, size/XS

#122 Remove Cluster SA i Role from Operator and move to OLM
  deploy/role.yaml
Labels: approved, lgtm, size/XS

#123 Remove Cluster SA i Role from Operator and move to OLM
  pkg/resources/reporter/deployments.go
Labels: approved, lgtm, size/XS

#125 Update permision in csv
  deploy/olm-catalog/ibm-licensing-operator/1.2.1/ibm-licensing-operator.v1.2.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#126 update operands digests
  Makefile
  deploy/crds/operator.ibm.com_v1alpha1_ibmlicenseservicereporter_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_ibmlicensing_cr.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.2.1/ibm-licensing-operator.v1.2.1.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/apis/operator/v1alpha1/helper.go
Labels: approved, lgtm, size/M

#127 delete product annotation
  deploy/olm-catalog/ibm-licensing-operator/1.2.1/ibm-licensing-operator.v1.2.1.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/resources/helper.go
Labels: approved, lgtm, size/XS

#128 update db operand digest
  deploy/olm-catalog/ibm-licensing-operator/1.2.1/ibm-licensing-operator.v1.2.1.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/apis/operator/v1alpha1/helper.go
Labels: approved, lgtm, size/S

#129 update memory limit
  deploy/olm-catalog/ibm-licensing-operator/1.2.1/ibm-licensing-operator.v1.2.1.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#130 update_digests
  deploy/olm-catalog/ibm-licensing-operator/1.2.1/ibm-licensing-operator.v1.2.1.clusterserviceversion.yaml
  pkg/apis/operator/v1alpha1/helper.go
Labels: approved, lgtm, size/S

#131 Operator should Update version in CR
  pkg/controller/ibmlicenseservicereporter/ibmlicenseservicereporter_controller.go
  pkg/controller/ibmlicensing/ibmlicensing_controller.go
  pkg/resources/reporter/helper.go
  pkg/resources/service/helper.go
Labels: approved, lgtm, size/M

#132 Fix missing certsource and too long wait times in reconcile loop
  pkg/apis/operator/v1alpha1/helper.go
  pkg/controller/ibmlicenseservicereporter/ibmlicenseservicereporter_controller.go
  pkg/resources/helper.go
  pkg/resources/reporter/receiver.go
  pkg/resources/reporter/volumes.go
  pkg/resources/service/containers.go
  pkg/resources/service/volumes.go
Labels: approved, lgtm, size/M

#133 fix for scorecard
  deploy/olm-catalog/ibm-licensing-operator/1.2.1/operator.ibm.com_ibmlicenseservicereporters_crd.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#135 update ui digest with update to 1.2.2
  deploy/olm-catalog/ibm-licensing-operator/1.2.2/ibm-licensing-operator.v1.2.2.clusterserviceversion.yaml
  pkg/apis/operator/v1alpha1/helper.go
  pkg/controller/ibmlicenseservicereporter/ibmlicenseservicereporter_controller.go
Labels: approved, lgtm, size/XS

#136 update to latest digests in latest csv and operator yaml in all images
  deploy/olm-catalog/ibm-licensing-operator/1.2.2/ibm-licensing-operator.v1.2.2.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#138 fix issue related with http and ocp
  pkg/controller/ibmlicenseservicereporter/ibmlicenseservicereporter_controller.go
  pkg/controller/ibmlicensing/ibmlicensing_controller.go
  pkg/resources/helper.go
  pkg/resources/reporter/services.go
  pkg/resources/service/containers.go
  pkg/resources/service/services.go
Labels: approved, lgtm, size/S

#137 move to using catalog source and delete dependency on operator market…
  README.md
  common/scripts/ibm_licensing_operator_install.sh
  docs/IBM_Licensing_solution_for_cloud_v1.2.pdf
Labels: approved, lgtm, size/L

#140 1.2.2 release changes
  README.md
  deploy/olm-catalog/ibm-licensing-operator/ibm-licensing-operator.package.yaml
Labels: approved, lgtm, size/L

#141 update operator to 1.2.3
  Makefile
  README.md
  deploy/crds/operator.ibm.com_v1alpha1_ibmlicenseservicereporter_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_ibmlicensing_cr.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.2.3/ibm-licensing-operator.v1.2.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.2.3/operator.ibm.com_ibmlicenseservicereporters_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.2.3/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/ibm-licensing-operator.package.yaml
  version/version.go
Labels: approved, lgtm, size/XXL

#139 Create E2E test for operator
  .github/workflows/kind.yml
  common/scripts/tests/.osdk-scorecard.yaml
  common/scripts/tests/tests.bats
Labels: approved, lgtm, size/L

#142 Update README.md add badge for build on KinD
  README.md
Labels: approved, lgtm, size/XS

#143 offline readme fix
  README.md
Labels: approved, lgtm, size/S

#144 e2e on artifactory
  .github/workflows/kind.yml
  common/scripts/tests/kind_config.yaml
  common/scripts/tests/tests.bats
Labels: approved, lgtm, size/S

#145 Update README.md
  README.md
Labels: approved, lgtm, size/XS

#146 Fix log
  common/scripts/tests/tests.bats
  pkg/controller/ibmlicenseservicereporter/ibmlicenseservicereporter_controller.go
  pkg/controller/ibmlicensing/ibmlicensing_controller.go
Labels: approved, lgtm, size/S

#148 update digest for 1.2.3
  common/scripts/tests/tests.bats
  deploy/olm-catalog/ibm-licensing-operator/1.2.3/ibm-licensing-operator.v1.2.3.clusterserviceversion.yaml
  pkg/apis/operator/v1alpha1/helper.go
Labels: approved, lgtm, size/XS

#149 update channel
  deploy/olm-catalog/ibm-licensing-operator/ibm-licensing-operator.package.yaml
Labels: approved, lgtm, size/XS

#150 race condition log error fix
  pkg/controller/ibmlicenseservicereporter/ibmlicenseservicereporter_controller.go
  pkg/controller/ibmlicensing/ibmlicensing_controller.go
Labels: approved, lgtm, size/M

#151 add development make prow jobs that pushes to scratch
  Makefile
  common/Makefile.common.mk
  common/scripts/config_docker_scratch.sh
Labels: approved, lgtm, size/M
