Repository IBM/ibm-licensing-operator, pull requests merged in 2020-08, with the labels that each got.

#86 Fix sender parameters
  deploy/crds/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.2.0/operator.ibm.com_ibmlicensings_crd.yaml
  pkg/apis/operator/v1alpha1/ibmlicensing_types.go
  pkg/controller/ibmlicensing/ibmlicensing_controller.go
  pkg/resources/containers.go
  pkg/resources/secrets.go
Labels: approved, lgtm, size/M

#88 update to use artifactory in prow build
  Makefile
  common/scripts/config_docker.sh
Labels: approved, lgtm, size/S

#87 License Service Reporter: First Integration
  cmd/manager/main.go
  deploy/crds/operator.ibm.com_ibmlicenseservicereporters_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_ibmlicenseservicereporter_cr.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.2.0/ibm-licensing-operator.v1.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.2.0/operator.ibm.com_ibmlicenseservicereporters_crd.yaml
  deploy/role.yaml
  go.mod
  go.sum
  pkg/apis/operator/v1alpha1/helper.go
  pkg/apis/operator/v1alpha1/ibmlicenseservicereporter_types.go
  pkg/apis/operator/v1alpha1/ibmlicensing_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_ibmlicenseservicereporter.go
  pkg/controller/ibmlicenseservicereporter/ibmlicenseservicereporter_controller.go
  pkg/controller/ibmlicensing/ibmlicensing_controller.go
  pkg/resources/containers.go
  pkg/resources/deployments.go
  pkg/resources/helper.go
  pkg/resources/reporter/database.go
  pkg/resources/reporter/deployments.go
  pkg/resources/reporter/helper.go
  pkg/resources/reporter/pvc.go
  pkg/resources/reporter/rbac.go
  pkg/resources/reporter/receiver.go
  pkg/resources/reporter/routing.go
  pkg/resources/reporter/secrets.go
  pkg/resources/reporter/services.go
  pkg/resources/reporter/volumes.go
  pkg/resources/service/containers.go
  pkg/resources/service/deployments.go
  pkg/resources/service/helper.go
  pkg/resources/service/rbac.go
  pkg/resources/service/routing.go
  pkg/resources/service/secrets.go
  pkg/resources/service/services.go
  pkg/resources/service/volumes.go
Labels: approved, lgtm, size/XXL

#90 Resource Limit set Defaults
  pkg/apis/operator/v1alpha1/helper.go
Labels: approved, lgtm, size/L

#91 Add UI Container to License Service Reporter
  deploy/crds/operator.ibm.com_ibmlicenseservicereporters_crd.yaml
  pkg/apis/operator/v1alpha1/helper.go
  pkg/apis/operator/v1alpha1/ibmlicenseservicereporter_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/resources/reporter/database.go
  pkg/resources/reporter/deployments.go
  pkg/resources/reporter/helper.go
  pkg/resources/reporter/receiver.go
  pkg/resources/reporter/services.go
  pkg/resources/reporter/ui.go
Labels: approved, lgtm, size/L

#92 Change rand function for security and fix Reporter CRD potential problem
  deploy/crds/operator.ibm.com_ibmlicenseservicereporters_crd.yaml
  deploy/crds/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.2.0/operator.ibm.com_ibmlicenseservicereporters_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.2.0/operator.ibm.com_ibmlicensings_crd.yaml
  pkg/apis/operator/v1alpha1/helper.go
  pkg/controller/ibmlicenseservicereporter/ibmlicenseservicereporter_controller.go
  pkg/controller/ibmlicensing/ibmlicensing_controller.go
  pkg/resources/helper.go
  pkg/resources/reporter/secrets.go
  pkg/resources/service/secrets.go
Labels: approved, lgtm, size/L

#93 Fix old images in manifest during prow build
  Makefile
  common/scripts/multiarch_image.sh
Labels: approved, lgtm, size/S

#94 Add GoReport to ReadMe
  README.md
  pkg/resources/service/containers.go
Labels: approved, lgtm, size/S

#95 update postgres db name key
  pkg/resources/reporter/helper.go
Labels: approved, lgtm, size/XS

#96 refactor reporter containers database variables to be taken directly …
  pkg/resources/reporter/database.go
  pkg/resources/reporter/helper.go
  pkg/resources/reporter/receiver.go
  pkg/resources/reporter/services.go
  pkg/resources/reporter/ui.go
Labels: approved, lgtm, size/L

#97 fix secret wrong namespace bug
  pkg/resources/service/secrets.go
Labels: approved, lgtm, size/XS

#98 set operand digest for ibm licensing image in csv
  deploy/olm-catalog/ibm-licensing-operator/1.2.0/ibm-licensing-operator.v1.2.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#100 fix database and ui
  pkg/resources/reporter/helper.go
  pkg/resources/reporter/ui.go
Labels: approved, lgtm, size/XS

#99 Route fix
  pkg/controller/ibmlicenseservicereporter/ibmlicenseservicereporter_controller.go
  pkg/resources/reporter/helper.go
  pkg/resources/reporter/routing.go
Labels: approved, lgtm, size/M

#101 change ui route to ui ingress
  deploy/crds/operator.ibm.com_v1alpha1_ibmlicenseservicereporter_cr.yaml
  pkg/controller/ibmlicenseservicereporter/ibmlicenseservicereporter_controller.go
  pkg/resources/reporter/routing.go
Labels: approved, lgtm, size/M

#105 1.2.0 beta fixes
  deploy/crds/operator.ibm.com_ibmlicenseservicereporters_crd.yaml
  deploy/crds/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_ibmlicensing_cr.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.2.0/ibm-licensing-operator.v1.2.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.2.0/operator.ibm.com_ibmlicenseservicereporters_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.2.0/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/ibm-licensing-operator.package.yaml
  deploy/operator.yaml
  pkg/apis/operator/v1alpha1/helper.go
  pkg/controller/ibmlicenseservicereporter/ibmlicenseservicereporter_controller.go
  pkg/resources/containers.go
  pkg/resources/helper.go
  pkg/resources/reporter/database.go
  pkg/resources/reporter/receiver.go
  pkg/resources/reporter/ui.go
  pkg/resources/service/containers.go
Labels: approved, lgtm, size/L

#106 sort functions in helper
  pkg/apis/operator/v1alpha1/helper.go
Labels: approved, lgtm, size/M

#107 make unnecessary public function private
  pkg/resources/reporter/database.go
  pkg/resources/reporter/volumes.go
Labels: approved, lgtm, size/XS

#110 update digests to newest ones
  deploy/olm-catalog/ibm-licensing-operator/1.2.0/ibm-licensing-operator.v1.2.0.clusterserviceversion.yaml
  pkg/apis/operator/v1alpha1/helper.go
Labels: approved, lgtm, size/S
