Repository IBM/ibm-licensing-operator, pull requests merged in 2020-04, with the labels that each got.

#25 move to version 1.1.0
  Makefile
  deploy/olm-catalog/ibm-licensing-operator/1.1.0/ibm-licensing-operator.v1.1.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.1.0/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/ibm-licensing-operator.package.yaml
  deploy/operator.yaml
  images/IBMLicensingOperatorParameters.csv
  images/IBMLicensingOperatorParameters.ods
  pkg/apis/operator/v1alpha1/helper.go
  version/version.go
Labels: approved, lgtm, size/XXL

#27 small fixes
  README.md
Labels: approved, lgtm, size/XS

#28 Update readme
  README.md
Labels: approved, lgtm, size/L

#29 Update readme
  README.md
Labels: approved, lgtm, size/L

#30 Add request and bindinfo
  deploy/olm-catalog/ibm-licensing-operator/1.1.0/ibm-licensing-operator.v1.1.0.clusterserviceversion.yaml
  pkg/controller/ibmlicensing/ibmlicensing_controller.go
Labels: approved, lgtm, size/M

#31 Update readme
  README.md
Labels: approved, lgtm, size/M

#33 change upload configmap to have correct key, value pair
  pkg/controller/ibmlicensing/ibmlicensing_controller.go
  pkg/resources/helper.go
Labels: approved, lgtm, size/S

#34 add default imageRegistry to CR, add csv scripts
  common/scripts/delete-csv.sh
  common/scripts/push-csv.sh
  deploy/crds/operator.ibm.com_v1alpha1_ibmlicensing_cr.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.1.0/ibm-licensing-operator.v1.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/L

#32 Update bindings structure
  deploy/olm-catalog/ibm-licensing-operator/1.1.0/ibm-licensing-operator.v1.1.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS
