Repository IBM/ibm-licensing-operator, pull requests merged in 2020-10, with the labels that each got.

#154 turn on test which check errors in log
  .github/workflows/ocp.yml
  common/scripts/tests/connect_ocp.sh
  common/scripts/tests/tests.bats
Labels: approved, lgtm, size/S

#155 Fixed problem with not available operator digest
  common/scripts/catalog_build.sh
Labels: approved, lgtm, size/XS

#156 turn off ibmcloud
  .github/workflows/ocp.yml
Labels: approved, lgtm, size/S

#157 add more tests
  .github/workflows/kind.yml
  .github/workflows/ocp.yml
  common/scripts/tests/tests.bats
  common/scripts/tests/tests_reporter.bats
Labels: approved, lgtm, size/L

#158 Development
  .github/workflows/kind.yml
  .github/workflows/ocp.yml
  Makefile
  common/Makefile.common.mk
  common/scripts/catalog/Dockerfile
  common/scripts/catalog_build.sh
  common/scripts/config_docker_scratch.sh
  common/scripts/tests/clear_ocp.sh
  common/scripts/tests/connect_ocp.sh
  common/scripts/tests/tests.bats
  common/scripts/tests/tests_reporter.bats
  pkg/controller/ibmlicenseservicereporter/ibmlicenseservicereporter_controller.go
  pkg/controller/ibmlicensing/ibmlicensing_controller.go
Labels: approved, lgtm, size/XL

#159 add status for ocp cluster for test
  README.md
Labels: approved, lgtm, size/XS

#162 Csv tests
  .github/workflows/kind.yml
  common/scripts/tests/.osdk-scorecard.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.3.0/ibm-licensing-operator.v1.3.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#163 run test every day
  .github/workflows/kind.yml
  .github/workflows/ocp.yml
Labels: approved, lgtm, size/XS

#165 Update codecoverage
  README.md
  pkg/controller/ibmlicenseservicereporter/ibmlicenseservicereporter_controller_test.go
  pkg/controller/ibmlicensing/ibmlicensing_controller_test.go
Labels: approved, lgtm, size/M

#164 Changed depl. strategy to recreate
  pkg/resources/reporter/deployments.go
Labels: approved, lgtm, size/XS

#166 finalizers permissions
  deploy/olm-catalog/ibm-licensing-operator/1.3.0/ibm-licensing-operator.v1.3.0.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/S

#167 upgrade operator-sdk and golang
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#168 Bk documentation rework
  README.md
  common/Makefile.common.mk
  docs/Content/Automatic_installation.md
  docs/Content/Backup_and_upgrade.md
  docs/Content/Configuration.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_on_OCP.md
  docs/Content/Installation_scenarios.md
  docs/Content/Preparing_for_installation.md
  docs/Content/Retrieving_data.md
  docs/Content/Troubleshooting.md
  docs/Content/Uninstalling.md
  docs/License_Service_main.md
  pkg/apis/operator/v1alpha1/helper.go
  pkg/apis/operator/v1alpha1/ibmlicensing_types.go
  pkg/controller/ibmlicenseservicereporter/ibmlicenseservicereporter_controller_test.go
  pkg/controller/ibmlicensing/ibmlicensing_controller_test.go
  pkg/resources/service/containers.go
Labels: approved, lgtm, size/XXL

#169 cache for isOpenShift and div it to isRoute and isOCPCertManager
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/apis/operator/v1alpha1/helper.go
  pkg/controller/ibmlicenseservicereporter/ibmlicenseservicereporter_controller.go
  pkg/controller/ibmlicensing/ibmlicensing_controller.go
  pkg/resources/helper.go
  pkg/resources/reporter/deployments.go
  pkg/resources/reporter/receiver.go
  pkg/resources/reporter/services.go
  pkg/resources/reporter/volumes.go
  pkg/resources/service/containers.go
  pkg/resources/service/deployments.go
  pkg/resources/service/services.go
  pkg/resources/service/volumes.go
Labels: approved, lgtm, size/L

#172 fix strange error with not found routes
  deploy/olm-catalog/ibm-licensing-operator/1.3.0/ibm-licensing-operator.v1.3.0.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/resources/helper.go
Labels: approved, lgtm, size/S

#175 Tests on Development branch
  Makefile
Labels: approved, size/XS

#176 dev fix multiarch
  Makefile
Labels: approved, size/XS

#171 Sender auto config with CR mod
  pkg/apis/operator/v1alpha1/helper.go
  pkg/controller/ibmlicenseservicereporter/ibmlicenseservicereporter_controller.go
  pkg/controller/ibmlicensing/ibmlicensing_controller.go
  pkg/resources/helper.go
  pkg/resources/reporter/helper.go
  pkg/resources/service/containers.go
Labels: approved, lgtm, size/L

#177 offline installation procedure update
  README.md
  docs/Content/Backup_and_upgrade.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_on_OCP.md
  docs/Content/Uninstalling.md
Labels: approved, lgtm, size/L

#178 Digests 271020
  deploy/olm-catalog/ibm-licensing-operator/1.3.0/ibm-licensing-operator.v1.3.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-licensing-operator/ibm-licensing-operator.package.yaml
  deploy/operator.yaml
  pkg/apis/operator/v1alpha1/helper.go
Labels: approved, lgtm, size/S

#180 update perm
  deploy/olm-catalog/ibm-licensing-operator/1.3.0/ibm-licensing-operator.v1.3.0.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/M
