Repository IBM/ibm-licensing-operator, pull requests merged in 2020-06, with the labels that each got.

#59 remove package dependency bou.ke/monkey, udpate dev to 1.1.3
  deploy/olm-catalog/ibm-licensing-operator/1.1.3/ibm-licensing-operator.v1.1.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.1.3/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/ibm-licensing-operator.package.yaml
  deploy/operator.yaml
  go.mod
  go.sum
  version/version.go
Labels: approved, lgtm, size/XXL

#61 fix upload config url
  pkg/resources/helper.go
Labels: approved, lgtm, size/XS

#62 update beta to 1.1.3
  deploy/olm-catalog/ibm-licensing-operator/1.1.3/ibm-licensing-operator.v1.1.3.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-licensing-operator/ibm-licensing-operator.package.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#64 update stable to 1.1.3
  deploy/olm-catalog/ibm-licensing-operator/ibm-licensing-operator.package.yaml
Labels: approved, lgtm, size/XS

#68 zLinux and pLinux support
  Makefile
  README.md
  common/Makefile.common.mk
  common/scripts/multiarch_image.sh
  deploy/olm-catalog/ibm-licensing-operator/1.2.0/ibm-licensing-operator.v1.2.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/resources/deployments.go
Labels: approved, lgtm, size/L

#70 fix docker images build args
  Makefile
Labels: approved, lgtm, size/XS

#71 change operator tag to latest as for now it is in dev only
  deploy/olm-catalog/ibm-licensing-operator/1.2.0/ibm-licensing-operator.v1.2.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#72 Update operand image
  README.md
  build/Dockerfile
  deploy/olm-catalog/ibm-licensing-operator/1.2.0/ibm-licensing-operator.v1.2.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/apis/operator/v1alpha1/helper.go
Labels: approved, lgtm, size/M
