Repository IBM/ibm-licensing-operator, pull requests merged in 2020-07, with the labels that each got.

#73 memory limit to 100MB
  README.md
  deploy/olm-catalog/ibm-licensing-operator/1.2.0/ibm-licensing-operator.v1.2.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#75 Go upgrade
  go.mod
Labels: approved, lgtm, size/XS

#76 Update README.md
  README.md
Labels: approved, lgtm, size/M

#78 ensure one operatorgroup exists
  common/scripts/ibm_licensing_operator_install.sh
Labels: approved, lgtm, size/S

#79 updated readme and script about supported platform
  README.md
  common/scripts/ibm_licensing_operator_install.sh
Labels: approved, lgtm, size/XS

#77 Readme clear navigation
  Makefile
  README.md
  images/IBMLicensingOperatorParameters.csv
  images/create-project-2.png
  images/create-project.png
  images/subscribe-licensing.png
Labels: approved, lgtm, size/L

#81 Controller update for configmap
  build/Dockerfile
  pkg/controller/ibmlicensing/ibmlicensing_controller.go
  pkg/resources/secrets.go
Labels: approved, lgtm, size/L

#82 add optional resources parameter
  deploy/crds/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.2.0/operator.ibm.com_ibmlicensings_crd.yaml
  pkg/apis/operator/v1alpha1/helper.go
  pkg/apis/operator/v1alpha1/ibmlicensing_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/resources/containers.go
  pkg/resources/helper.go
Labels: approved, lgtm, size/M

#83 add sender parameters
  deploy/crds/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.2.0/operator.ibm.com_ibmlicensings_crd.yaml
  pkg/apis/operator/v1alpha1/ibmlicensing_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/resources/containers.go
Labels: approved, lgtm, size/L
