Repository IBM/ibm-licensing-operator, pull requests merged in 2021-07, with the labels that each got.

#421 Removed ServiceAccounts
  Makefile
  bundle/manifests/ibm-license-service_v1_serviceaccount.yaml
  bundle/manifests/ibm-licensing-operator_v1_serviceaccount.yaml
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
Labels: approved, lgtm, size/M

#422 Certification fixes
  README.md
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
Labels: approved, size/XS

#424 Ibmlicnesingmetadata crd
  Makefile
  PROJECT
  api/v1alpha1/ibmlicensing_types.go
  api/v1alpha1/ibmlicensingmetadata_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/ibm-license-service_v1_serviceaccount.yaml
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/ibm-licensing-operator_v1_serviceaccount.yaml
  bundle/manifests/operator.ibm.com_ibmlicensingmetadatas.yaml
  config/crd/bases/operator.ibm.com_ibmlicensingmetadatas.yaml
  config/crd/kustomization.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/rbac/role_operands.yaml
  config/samples/operator_v1alpha1_ibmlicensingmetadata.yaml
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
Labels: approved, lgtm, size/L

#425 Fix cert
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#420 Ingress upgrade v1beta1 -> v1
  .github/workflows/kind.yml
  api/v1alpha1/ibmlicensing_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  controllers/ibmlicenseservicereporter_controller.go
  controllers/ibmlicensing_controller.go
  controllers/resources/helper.go
  controllers/resources/reporter/routing.go
  controllers/resources/service/routing.go
  go.sum
Labels: approved, size/L

#427 Licensingmetadata future
  .github/workflows/kind.yml
  README.md
  api/v1alpha1/ibmlicenseservicereporter_types.go
  api/v1alpha1/ibmlicensing_types.go
  api/v1alpha1/ibmlicensingmetadata_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicenseservicereporters.yaml
  bundle/manifests/operator.ibm.com_ibmlicensingmetadatas.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  common/config/.hadolint.yml
  config/crd/bases/operator.ibm.com_ibmlicenseservicereporters.yaml
  config/crd/bases/operator.ibm.com_ibmlicensingmetadatas.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  controllers/ibmlicenseservicereporter_controller.go
  controllers/ibmlicensing_controller.go
  controllers/resources/helper.go
  controllers/resources/reporter/routing.go
  controllers/resources/service/routing.go
  go.sum
Labels: approved, size/L

#430 update 1.6 docs
  README.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
  docs/Content/Troubleshooting.md
  docs/License_Service_main.md
Labels: approved, lgtm, size/S

#429 Update version.go
  Makefile
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: approved, lgtm, size/M

#428 Ibmlicnesingmetadata crd
  Makefile
  PROJECT
  api/v1alpha1/ibmlicensing_types.go
  api/v1alpha1/ibmlicensingmetadata_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensingmetadatas.yaml
  config/crd/bases/operator.ibm.com_ibmlicensingmetadatas.yaml
  config/crd/kustomization.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/rbac/role_operands.yaml
  config/samples/operator_v1alpha1_ibmlicensingmetadata.yaml
Labels: approved, lgtm, size/L

#431 Reporter route fix
  Makefile
  controllers/ibmlicenseservicereporter_controller.go
  controllers/ibmlicensing_controller.go
  controllers/resources/helper.go
  controllers/resources/reporter/routing.go
Labels: approved, lgtm, size/M

#432 Fix formatting of internal objects annotation
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#433 Update UBI image for License Service Operator #48515
  Dockerfile
Labels: approved, lgtm, size/XS
