Repository IBM/ibm-licensing-operator, pull requests merged in 2021-02, with the labels that each got.

#287 Added possibility to disable RHMP
  controllers/ibmlicensing_controller.go
  controllers/resources/helper.go
  controllers/resources/service/services.go
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/ibm-licensing-operator.v1.4.0.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/L

#288 new api for new meterdef
  controllers/resources/service/meter_definition.go
Labels: approved, lgtm, size/S

#289 new api for new meterdef1
  controllers/resources/service/meter_definition.go
Labels: approved, lgtm, size/XS

#290 NetworkPolicy fix for LS
  controllers/resources/service/networking.go
Labels: approved, lgtm, size/XS

#291 Arun Request for change
  controllers/resources/service/meter_definition.go
Labels: approved, lgtm, size/XS

#278 coverage
  .github/workflows/kind.yml
  Makefile
  common/scripts/codecov.sh
Labels: approved, lgtm, size/S

#292 Meterdefinitions permission
  controllers/ibmlicensing_controller.go
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/ibm-licensing-operator.v1.4.0.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/S

#294 Meterdefinitions permission fix
  controllers/ibmlicensing_controller.go
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/ibm-licensing-operator.v1.4.0.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/XS

#295 protobuf upgrade to 1.3.2
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#296 protobuf upgrade to 1.3.2
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#293 coverage on ocp
  .github/workflows/kind.yml
  .github/workflows/ocp.yml
  Makefile
  common/scripts/codecov.sh
  controllers/ibmlicenseservicereporter_controller.go
  controllers/ibmlicenseservicereporter_controller_test.go
  controllers/ibmlicensing_controller_test.go
  controllers/suite_test.go
Labels: approved, lgtm, size/L

#297 Changed usage service labels
  controllers/resources/service/helper.go
  controllers/resources/service/services.go
Labels: approved, lgtm, size/S

#298 unit tests for RHMP
  Makefile
  common/scripts/tests/clear_ocp.sh
  controllers/ibmlicensing_controller_test.go
Labels: approved, lgtm, size/M

#300 Rhmp resources tests
  controllers/ibmlicensing_controller_test.go
  controllers/resources/service/meter_definition.go
  controllers/resources/service/networking.go
Labels: approved, lgtm, size/M

#299 second meter def for deep dive
  controllers/ibmlicensing_controller.go
  controllers/ibmlicensing_controller_test.go
  controllers/resources/service/meter_definition.go
Labels: approved, lgtm, size/M

#301 update comment piotr
  controllers/resources/service/meter_definition.go
Labels: approved, lgtm, size/XS

#302 MeterDefinition owner
  controllers/ibmlicensing_controller.go
Labels: approved, lgtm, size/XS

#303 copyright 2021
  .github/workflows/kind.yml
  .github/workflows/ocp.yml
  Dockerfile
  Makefile
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/helper.go
  api/v1alpha1/ibmlicenseservicereporter_types.go
  api/v1alpha1/ibmlicensing_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  common/scripts/catalog_build.sh
  common/scripts/codecov.sh
  common/scripts/config_docker.sh
  common/scripts/config_docker_scratch.sh
  common/scripts/delete-csv.sh
  common/scripts/get-image-sha.sh
  common/scripts/gobuild.sh
  common/scripts/ibm_licensing_operator_install.sh
  common/scripts/install-operator-sdk.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/lint_go.sh
  common/scripts/multiarch_image.sh
  common/scripts/non_ocp_install.sh
  common/scripts/push-csv.sh
  common/scripts/tests/clear_ocp.sh
  common/scripts/tests/connect_ocp.sh
  common/scripts/tests/tests.bats
  common/scripts/tests/tests_reporter.bats
  controllers/ibmlicenseservicereporter_controller.go
  controllers/ibmlicenseservicereporter_controller_test.go
  controllers/ibmlicensing_controller.go
  controllers/ibmlicensing_controller_test.go
  controllers/resources/containers.go
  controllers/resources/deployments.go
  controllers/resources/helper.go
  controllers/resources/reporter/database.go
  controllers/resources/reporter/deployments.go
  controllers/resources/reporter/helper.go
  controllers/resources/reporter/pvc.go
  controllers/resources/reporter/rbac.go
  controllers/resources/reporter/receiver.go
  controllers/resources/reporter/routing.go
  controllers/resources/reporter/secrets.go
  controllers/resources/reporter/services.go
  controllers/resources/reporter/ui.go
  controllers/resources/reporter/volumes.go
  controllers/resources/service/containers.go
  controllers/resources/service/deployments.go
  controllers/resources/service/helper.go
  controllers/resources/service/meter_definition.go
  controllers/resources/service/networking.go
  controllers/resources/service/routing.go
  controllers/resources/service/secrets.go
  controllers/resources/service/service_monitor.go
  controllers/resources/service/services.go
  controllers/resources/service/volumes.go
  controllers/resources/volumes.go
  controllers/suite_test.go
  hack/boilerplate.go.txt
  main.go
  version/version.go
Labels: approved, lgtm, size/L

#304 fix meter definition
  controllers/resources/service/meter_definition.go
Labels: approved, lgtm, size/XS

#305 fix servis monitor
  controllers/resources/service/service_monitor.go
Labels: approved, lgtm, size/XS

#308 Update to 1.4.1
  .github/workflows/kind.yml
  Makefile
  common/scripts/tests/.osdk-scorecard.yaml
  common/scripts/tests/tests.bats
  common/scripts/tests/tests_reporter.bats
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  deploy/crds/operator.ibm.com_v1alpha1_ibmlicenseservicereporter_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_ibmlicensing_cr.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.4.1/ibm-licensing-operator.v1.4.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.4.1/operator.ibm.com_ibmlicenseservicereporters_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.4.1/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/ibm-licensing-operator.package.yaml
  deploy/operator.yaml
  version/version.go
Labels: approved, lgtm, size/XXL

#307 Migration from bats
  .github/workflows/kind.yml
  .github/workflows/ocp.yml
  common/scripts/tests/tests.bats
  common/scripts/tests/tests_reporter.bats
  controllers/ibmlicenseservicereporter_controller_test.go
  controllers/ibmlicensing_controller_test.go
Labels: approved, lgtm, size/XL
