Repository IBM/ibm-licensing-operator, pull requests merged in 2021-09, with the labels that each got.

#465 updated golang image to 1.17-alpine
  CONTRIBUTING.md
  common/scripts/catalog/Dockerfile
Labels: approved, size/XS, lgtm

#466 golang image updated to 1.17-alpine
  .github/workflows/kind.yml
  .github/workflows/ocp.yml
  common/scripts/catalog/Dockerfile
Labels: approved, size/XS, lgtm

#460 add hyper threading support
  api/v1alpha1/features.go
  api/v1alpha1/features/hyper_threading.go
  api/v1alpha1/ibmlicensing_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  controllers/resources/service/containers.go
Labels: approved, lgtm, size/L

#468 dummy commit to check builds
  README.md
Labels: approved, size/XS, lgtm

#469 update OCP support
  docs/Content/Install_from_scratch.md
  docs/Content/Install_on_OCP.md
  docs/Content/Install_without_OLM.md
  docs/Content/Preparing_for_installation.md
Labels: approved, lgtm, size/S

#474 Update 1.9
  Makefile
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: approved, lgtm, size/M

#470 update supported systems
  docs/Content/Install_from_scratch.md
  docs/Content/Install_on_OCP.md
  docs/Content/Install_without_OLM.md
  docs/Content/Preparing_for_installation.md
Labels: approved, lgtm, size/S

#475 Fix catalog latest build
  Makefile
Labels: approved, size/XS, lgtm

#473 Offline install fix 1.7
  docs/Content/Install_offline.md
Labels: approved, lgtm, size/M

#477 Offline instalation 1.8
  docs/Content/Install_offline.md
Labels: approved, lgtm, size/M

#476 Update operator sdk and add relatedImages automation
  .github/workflows/kind.yml
  PROJECT
  bundle.Dockerfile
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicenseservicereporters.yaml
  bundle/manifests/operator.ibm.com_ibmlicensingmetadatas.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XXL

#471 Add version labels and file
  Dockerfile
  Makefile
Labels: approved, lgtm, size/S

#478 Bk doc update 1.8
  README.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_on_OCP.md
  docs/Content/Install_without_OLM.md
  docs/Content/Installation_scenarios.md
  docs/Content/Preparing_for_installation.md
  docs/License_Service_main.md
Labels: approved, lgtm, size/S

#472 Fix offline installation procedure
  docs/Content/Install_offline.md
Labels: approved, lgtm, size/M

#479 fix readme for installation without olm
  api/v1alpha1/zz_generated.deepcopy.go
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
  docs/Content/Troubleshooting.md
  docs/Content/Uninstalling.md
  docs/License_Service_main.md
Labels: approved, lgtm, size/L

#480 fix readme for install without olm and other cosmetic changes
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
  docs/Content/Troubleshooting.md
  docs/Content/Uninstalling.md
  docs/License_Service_main.md
Labels: approved, lgtm, size/L

#481 TS006071064 Warning: Failed to update pod status
  controllers/ibmlicensing_controller.go
Labels: approved, size/XS, lgtm
