Repository IBM/ibm-licensing-operator, pull requests merged in 2021-01, with the labels that each got.

#251 RHMP enhancements reverted
  controllers/ibmlicensing_controller.go
  controllers/resources/service/helper.go
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/ibm-licensing-operator.v1.4.0.clusterserviceversion.yaml
  deploy/role.yaml
  main.go
Labels: approved, lgtm, size/M

#253 fix multiarch
  common/scripts/multiarch_image.sh
Labels: approved, lgtm, size/S

#252 Revert "Revert "rhmp bug fixes and enhancements (#243)" (#251)"
  common/scripts/multiarch_image.sh
  controllers/ibmlicensing_controller.go
  controllers/resources/service/helper.go
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/ibm-licensing-operator.v1.4.0.clusterserviceversion.yaml
  deploy/role.yaml
  main.go
Labels: approved, lgtm, size/M

#254 fix multiarch
  common/scripts/multiarch_image.sh
Labels: approved, lgtm, size/S

#255 fix multiarch
  Makefile
Labels: approved, lgtm, size/S

#256 Rhmp role
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/operator.ibm.com_ibmlicensings_crd.yaml
Labels: approved, lgtm, size/XS

#257 fix unitests
  Makefile
  controllers/ibmlicensing_controller_test.go
  controllers/suite_test.go
Labels: approved, lgtm, size/M

#259 Digest Update 1610119087
  deploy/olm-catalog/ibm-licensing-operator/1.3.2/ibm-licensing-operator.v1.3.2.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, size/S

#260 Digest Update 1610119255
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/ibm-licensing-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#261 add sa for meterdefinition
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/ibm-licensing-operator.v1.4.0.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/S

#258 Aobrzut units
  .github/workflows/ocp.yml
  Makefile
  controllers/ibmlicensing_controller_test.go
  controllers/suite_test.go
Labels: approved, lgtm, size/L

#262 Digest Update 1610445537
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/ibm-licensing-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#263 network policy scheme added
  main.go
Labels: approved, lgtm, size/XS

#265 update UBI
  build/Dockerfile
Labels: approved, lgtm, size/XS

#266 update UBI
  Dockerfile
Labels: approved, lgtm, size/XS

#267 Digest Update 1610529576
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/ibm-licensing-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#270 updated network policy version
  controllers/ibmlicensing_controller.go
  controllers/resources/service/networking.go
  main.go
Labels: approved, lgtm, size/S

#269 Adopt operand digest auto-update in the operator #43681
  Makefile
  api/v1alpha1/helper.go
  common/scripts/get-image-sha.sh
  common/scripts/tests/tests.bats
  common/scripts/tests/tests_reporter.bats
  config/crd/bases/operator.ibm.com_ibmlicenseservicereporters.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  config/manager/manager.yaml
  deploy/crds/operator.ibm.com_ibmlicenseservicereporters_crd.yaml
  deploy/crds/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/ibm-licensing-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/operator.ibm.com_ibmlicenseservicereporters_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/operator.yaml
  docs/Content/Troubleshooting.md
Labels: approved, lgtm, size/L

#272 Labels update for NetworkPolicy
  controllers/resources/service/helper.go
  controllers/resources/service/networking.go
Labels: approved, lgtm, size/XS

#274 Adopt operand digest auto-update in the operator #43681
  common/scripts/get-image-sha.sh
  deploy/crds/operator.ibm.com_ibmlicenseservicereporters_crd.yaml
  deploy/crds/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.3.2/ibm-licensing-operator.v1.3.2.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.3.2/operator.ibm.com_ibmlicenseservicereporters_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.3.2/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/operator.yaml
  docs/Content/Troubleshooting.md
  pkg/apis/operator/v1alpha1/helper.go
Labels: approved, size/L

#275 service monitor tls update
  config/rbac/role.yaml
  controllers/ibmlicenseservicereporter_controller.go
  controllers/ibmlicensing_controller.go
  controllers/resources/helper.go
  controllers/resources/service/containers.go
  controllers/resources/service/helper.go
  controllers/resources/service/service_monitor.go
  controllers/resources/service/services.go
  controllers/resources/service/volumes.go
Labels: approved, lgtm, size/M

#277 fix DFATAL with Log
  common/scripts/codecov.sh
  controllers/resources/helper.go
  controllers/resources/reporter/helper.go
Labels: approved, lgtm, size/M

#273 new meterdefinition
  controllers/ibmlicensing_controller.go
  controllers/resources/service/meter_definition.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, size/XXL

#280 fix log
  controllers/ibmlicensing_controller.go
Labels: approved, lgtm, size/XS

#279 network policy namespace selector updated
  controllers/resources/service/helper.go
Labels: approved, lgtm, size/XS

#282 add chargeback options to csv and ls crd
  api/v1alpha1/helper.go
  api/v1alpha1/ibmlicensing_types.go
  controllers/resources/service/containers.go
  deploy/crds/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/ibm-licensing-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/operator.ibm.com_ibmlicensings_crd.yaml
Labels: approved, lgtm, size/M

#283 updated node affinity label
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/ibm-licensing-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#284 make instance namespace optional
  api/v1alpha1/helper.go
  api/v1alpha1/ibmlicensing_types.go
  controllers/ibmlicensing_controller.go
  deploy/crds/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_ibmlicensing_cr.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/ibm-licensing-operator.v1.4.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/operator.ibm.com_ibmlicensings_crd.yaml
  main.go
Labels: approved, lgtm, size/M

#281 Add Usage container
  Makefile
  api/v1alpha1/helper.go
  api/v1alpha1/ibmlicensing_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  controllers/ibmlicensing_controller.go
  controllers/ibmlicensing_controller_test.go
  controllers/resources/service/containers.go
  controllers/resources/service/deployments.go
  controllers/resources/service/helper.go
  controllers/resources/service/meter_definition.go
  controllers/resources/service/services.go
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/ibm-licensing-operator.v1.4.0.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/role.yaml
  go.mod
  go.sum
Labels: approved, lgtm, size/XL

#285 crd update
  deploy/crds/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.4.0/operator.ibm.com_ibmlicensings_crd.yaml
Labels: approved, lgtm, size/L
