Repository IBM/ibm-licensing-operator, pull requests merged in 2021-06, with the labels that each got.

#399 Bug 46781
  controllers/resources/helper.go
Labels: approved, lgtm, size/S

#401 Bk 1.4 cs name change
  README.md
  docs/Content/Preparing_for_installation.md
  docs/Content/Retrieving_data.md
  docs/Content/Troubleshooting.md
  docs/License_Service_main.md
Labels: approved, lgtm, size/M

#403 doc updates
  README.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_on_OCP.md
  docs/Content/Install_without_OLM.md
  docs/Content/Preparing_for_installation.md
  docs/Content/Retrieving_data.md
  docs/Content/Troubleshooting.md
  docs/License_Service_main.md
Labels: approved, lgtm, size/M

#404 fix CASE bundle linter error
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
Labels: approved, size/XS

#405 UBI update
  Dockerfile
Labels: approved, lgtm, size/XS

#400 rhmp override chargeback to true because it is always needed for it t…
  api/v1alpha1/helper.go
Labels: approved, lgtm, size/XS

#408 Update 1.6.0
  Makefile
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: approved, lgtm, size/M

#412 S kdev
  docs/Content/Configuration.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_on_OCP.md
Labels: approved, lgtm, size/M

#414 Crd v1 update
  Makefile
  bundle/manifests/operator.ibm.com_ibmlicenseservicereporters.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  config/crd/bases/operator.ibm.com_ibmlicenseservicereporters.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
Labels: approved, lgtm, size/XXL

#416 minor doc fix
  docs/Content/Install_on_OCP.md
Labels: approved, lgtm, size/XS

#415 Bk doc updates 1.5
  docs/Content/Install_on_OCP.md
Labels: approved, lgtm, size/XS

#417 LSR not available without CP on OCP
  README.md
  docs/Content/Automatic_installation.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_on_OCP.md
  docs/Content/Install_without_OLM.md
  docs/Content/Installation_scenarios.md
Labels: approved, lgtm, size/M

#418 LSR not available without CP on OCP (#417)
  README.md
  docs/Content/Automatic_installation.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_on_OCP.md
  docs/Content/Install_without_OLM.md
  docs/Content/Installation_scenarios.md
Labels: approved, lgtm, size/M

#419 Update description
  Makefile
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS
