Repository IBM/ibm-licensing-operator, pull requests merged in 2021-11, with the labels that each got.

#493 update commands
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
  docs/Content/Uninstalling.md
Labels: approved, size/S

#495 update 1.11
  Makefile
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: approved, lgtm, size/M

#497 update marketplace crd
  Makefile
  docs/Content/Uninstalling.md
Labels: approved, size/XS, lgtm

#498 dummy commit to rebuild image with latest base image
  README.md
  base_images.json
Labels: approved, size/XS, lgtm

#499 dummy commit to rebuild image with latest base image
  base_images.json
Labels: approved, size/XS, lgtm

#501 fix version issues
  deploy/operator.yaml
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
  docs/Content/Troubleshooting.md
  docs/Content/Uninstalling.md
Labels: approved, lgtm, size/M

#500 RBAC configuration for Authn/Authz LS API access
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/rbac/role_binding.yaml
  config/rbac/role_operands.yaml
Labels: approved, size/M

#504 update documentation for 1.10
  README.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
  docs/Content/Installation_scenarios.md
  docs/Content/Preparing_for_installation.md
  docs/License_Service_main.md
Labels: approved, lgtm, size/S

#506 add note to indicate the doc is outdated
  docs/Content/Automatic_installation.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_on_OCP.md
  docs/Content/Install_without_OLM.md
  docs/Content/Installation_scenarios.md
Labels: approved, lgtm, size/S

#510 adding the note about outdated install procedure to 1.5 branch
  docs/Content/Automatic_installation.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_on_OCP.md
  docs/Content/Install_without_OLM.md
  docs/Content/Installation_scenarios.md
Labels: approved, lgtm, size/S

#508 update documentation with a note about outdated install procedures
  docs/Content/Automatic_installation.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_on_OCP.md
  docs/Content/Install_without_OLM.md
  docs/Content/Installation_scenarios.md
  docs/Content/Preparing_for_installation.md
  docs/License_Service_main.md
Labels: approved, lgtm, size/S

#509 update the note about outdated installation procedure
  docs/Content/Automatic_installation.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_on_OCP.md
  docs/Content/Install_without_OLM.md
  docs/Content/Installation_scenarios.md
Labels: approved, lgtm, size/S

#511 Bk doc outdated note 1.4
  docs/Content/Automatic_installation.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_on_OCP.md
  docs/Content/Install_without_OLM.md
  docs/Content/Installation_scenarios.md
Labels: approved, lgtm, size/S

#512 add note about outdated installation procedures for 1.3 branch
  docs/Content/Automatic_installation.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_on_OCP.md
  docs/Content/Install_without_OLM.md
  docs/Content/Installation_scenarios.md
Labels: approved, lgtm, size/S

#514 update note about outdated documentation
  README.md
Labels: size/XS, lgtm

#513 add note about outdated documentation
  README.md
Labels: size/XS, lgtm

#517 update hardware requirements
  docs/Content/Preparing_for_installation.md
  docs/License_Service_main.md
Labels: approved, lgtm, size/M

#505 add new sa ibm-license-service-restricted
  Makefile
  api/v1alpha1/features.go
  api/v1alpha1/ibmlicensing_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  common/scripts/updateCSV/saCP2.yaml
  common/scripts/updateCSV/saP2.yaml
  common/scripts/updateCSV/updateCP2.yaml
  common/scripts/updateCSV/updateP2.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  config/rbac/role_binding.yaml
  config/rbac/role_operands.yaml
  config/rbac/service_account.yaml
  controllers/resources/deployments.go
  controllers/resources/service/containers.go
  controllers/resources/service/deployments.go
  controllers/resources/service/helper.go
  docs/Content/Preparing_for_installation.md
Labels: approved, lgtm, size/L

#515 Rbac auth
  Makefile
  api/v1alpha1/features.go
  api/v1alpha1/features/auth.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  common/scripts/updateCSV/saAccessCP.yaml
  common/scripts/updateCSV/updateAccessCP.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  config/rbac/role_binding.yaml
  config/rbac/role_operands.yaml
  config/rbac/service_account.yaml
  controllers/resources/service/containers.go
Labels: approved, lgtm, size/L

#520 Fixed permisions for restricted
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/rbac/role_operands.yaml
Labels: approved, lgtm, size/M

#521 Namespace scope tweaks
  OWNERS
  controllers/ibmlicensing_controller.go
Labels: approved, size/XS, lgtm

#519 Remove Codecov
  .github/workflows/ocp.yml
  Makefile
  README.md
  SECURITY_CONTACTS
  common/scripts/codecov.sh
Labels: approved, lgtm, size/L
