Repository IBM/ibm-licensing-operator, pull requests merged in 2021-12, with the labels that each got.

#525 Release 1.11
  docs/Content/Install_from_scratch.md
Labels: size/XS

#522 Update 1.12
  Makefile
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: approved, lgtm, size/M

#527 update offline instruction - lukaszG
  README.md
  docs/Content/Install_on_OCP.md
  docs/Content/Installation_scenarios.md
  docs/Content/Preparing_for_installation.md
  docs/License_Service_main.md
Labels: size/S

#530 update docs
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_on_OCP.md
  docs/Content/Installation_scenarios.md
  docs/Content/Retrieving_data.md
  docs/License_Service_main.md
Labels: approved, size/S

#534 Update to 1.3.4
  .github/workflows/kind.yml
  Makefile
  common/scripts/tests/.osdk-scorecard.yaml
  common/scripts/tests/tests.bats
  common/scripts/tests/tests_reporter.bats
  deploy/crds/operator.ibm.com_v1alpha1_ibmlicenseservicereporter_cr.yaml
  deploy/crds/operator.ibm.com_v1alpha1_ibmlicensing_cr.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.3.4/ibm-licensing-operator.v1.3.4.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.3.4/operator.ibm.com_ibmlicenseservicereporters_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/1.3.4/operator.ibm.com_ibmlicensings_crd.yaml
  deploy/olm-catalog/ibm-licensing-operator/ibm-licensing-operator.package.yaml
  deploy/operator.yaml
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
  docs/Content/Troubleshooting.md
  docs/Content/Uninstalling.md
  version/version.go
Labels: approved, lgtm, size/XXL

#533 Automatic RHMP integration
  api/v1alpha1/helper.go
  api/v1alpha1/ibmlicensing_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  controllers/ibmlicensing_controller.go
  controllers/resources/helper.go
Labels: approved, lgtm, size/M

#535 Fix feature status
  api/v1alpha1/helper.go
  controllers/ibmlicensing_controller.go
Labels: approved, lgtm, size/S

#536 Fix feature status
  controllers/ibmlicensing_controller.go
Labels: approved, size/XS, lgtm
