Repository IBM/ibm-licensing-operator, pull requests merged in 2021-03, with the labels that each got.

#310 run test on varius k8s
  .github/workflows/kind.yml
  .github/workflows/ocp.yml
  controllers/ibmlicensing_controller_test.go
Labels: approved, lgtm, size/M

#313 add replace
  deploy/olm-catalog/ibm-licensing-operator/1.4.1/ibm-licensing-operator.v1.4.1.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#312 Development branch configuration
  .github/workflows/kind.yml
  .github/workflows/ocp.yml
  Makefile
Labels: approved, lgtm, size/M

#314 Development branch build fix
  .github/workflows/kind.yml
Labels: approved, size/XS

#315 Change operator image tog for development branch
  Makefile
Labels: approved, size/XS

#318 dummy commit
  bundle.Dockerfile
Labels: approved, lgtm, size/XS

#320 RHMP and chargeback
  api/v1alpha1/helper.go
  controllers/ibmlicensing_controller_test.go
Labels: approved, lgtm, size/S

#323 Update script channel to v3
  common/scripts/ibm_licensing_operator_install.sh
Labels: approved, lgtm, size/S

#325 Merge changes
  common/scripts/ibm_licensing_operator_install.sh
Labels: lgtm, size/S

#326 RHMP MeterDef for new API
  controllers/ibmlicensing_controller_test.go
  controllers/resources/service/meter_definition.go
Labels: approved, lgtm, size/M

#324 Bk documentation mar11
  README.md
  docs/Content/Automatic_installation.md
  docs/Content/Configuration.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_on_OCP.md
  docs/Content/Install_without_OLM.md
  docs/Content/Installation_scenarios.md
  docs/Content/Preparing_for_installation.md
  docs/Content/Retrieving_data.md
  docs/Content/Troubleshooting.md
  docs/Content/Uninstalling.md
  docs/License_Service_main.md
Labels: approved, lgtm, size/M

#327 adding back datasource:datacollector
  README.md
  docs/Content/Configuration.md
  docs/Content/Install_offline.md
  docs/Content/Install_on_OCP.md
  docs/Content/Install_without_OLM.md
Labels: approved, lgtm, size/XS

#328 add commit id and build date to operator
  Dockerfile
  Makefile
  main.go
Labels: approved, lgtm, size/S

#329 bundle regenerated
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/crd/bases/operator.ibm.com_ibmlicenseservicereporters.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: approved, lgtm, size/M

#331 Resolve conflicts
  README.md
  common/scripts/ibm_licensing_operator_install.sh
  docs/Content/Automatic_installation.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_on_OCP.md
  docs/Content/Install_without_OLM.md
  docs/Content/Installation_scenarios.md
  docs/Content/Preparing_for_installation.md
  docs/Content/Retrieving_data.md
  docs/Content/Troubleshooting.md
  docs/License_Service_main.md
Labels: approved, lgtm, size/M

#333 fix bundle format
  Makefile
  bundle.Dockerfile
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/L

#330 scorecard for bundle format
  .github/workflows/kind.yml
  Makefile
  bundle.Dockerfile
  bundle/tests/scorecard/config.yaml
Labels: approved, lgtm, size/L

#334 fix mutliarch for dev
  Makefile
Labels: approved, lgtm, size/XS

#335 Update Makefile
  Makefile
Labels: approved, lgtm, size/XS

#336 fix mutliarch for dev
  Makefile
Labels: approved, lgtm, size/M

#338 CatalogSource image generation during multiarch task
  Makefile
Labels: approved, lgtm, size/XS

#339 Bk update channel mar25
  docs/Content/Backup_and_upgrade.md
  docs/Content/Upgrading_to_14x.md
  docs/License_Service_main.md
Labels: approved, lgtm, size/M

#341 make catalogbuild
  Makefile
Labels: approved, lgtm, size/S

#342 fix catalog source
  Makefile
Labels: approved, lgtm, size/S

#343 Multiarch CatalogSource
  Makefile
Labels: approved, lgtm, size/S

#344 Mutliarch cataogsource
  Makefile
Labels: approved, lgtm, size/XS

#345 New ibm-licensing-info CM and bind info update
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensingbindinfo.yaml
  controllers/ibmlicensing_controller.go
  controllers/resources/service/helper.go
  controllers/resources/service/secrets.go
  deploy-old/olm-catalog/ibm-licensing-operator/1.5.0/ibm-licensing-operator.v1.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#346 Backport142
  api/v1alpha1/helper.go
  controllers/ibmlicensing_controller_test.go
  controllers/resources/service/meter_definition.go
Labels: approved, lgtm, size/M

#347 Update Makefile for catalogsurce multiarch
  Makefile
Labels: approved, lgtm, size/XS

#349 package name fix
  bundle/metadata/annotations.yaml
Labels: approved, lgtm, size/XS
