Repository IBM/ibm-licensing-operator, pull requests merged in 2021-04, with the labels that each got.

#350 fixed catalog build
  common/scripts/catalog_build.sh
Labels: approved, lgtm, size/XS

#352 channel update for test catalogsource
  Makefile
Labels: approved, lgtm, size/XS

#351 Update Install_without_OLM.md
  README.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
  docs/Content/Troubleshooting.md
  docs/Content/Uninstalling.md
Labels: approved, lgtm, size/M

#353 fix image in bundle
  Makefile
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, lgtm, size/XS

#354 Documentation updates for 1.4
  README.md
  docs/Content/Automatic_installation.md
  docs/Content/Backup_and_upgrade.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_on_OCP.md
  docs/Content/Install_without_OLM.md
  docs/Content/Installation_scenarios.md
  docs/Content/Preparing_for_installation.md
  docs/Content/Retrieving_data.md
  docs/Content/Troubleshooting.md
  docs/Content/Upgrading_to_14x.md
  docs/License_Service_main.md
Labels: approved, lgtm, size/M

#356 multiarch fix for catalogsource
  Makefile
Labels: approved, lgtm, size/XS

#355 aws_to_roks
  .github/workflows/ocp.yml
  Makefile
Labels: approved, size/S

#357 Update Install_offline.md
  docs/Content/Install_offline.md
Labels: approved, lgtm, size/S

#358 Update Install_offline.md
  docs/Content/Install_offline.md
Labels: approved, lgtm, size/XS

#360 updated postgres image version
  common/scripts/tests/tests_reporter.bats
  deploy/olm-catalog/ibm-licensing-operator/1.3.2/ibm-licensing-operator.v1.3.2.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS

#361 update postgres version
  Makefile
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  deploy-old/olm-catalog/ibm-licensing-operator/1.5.0/ibm-licensing-operator.v1.5.0.clusterserviceversion.yaml
  deploy-old/operator.yaml
  docs/Content/Troubleshooting.md
Labels: approved, lgtm, size/S

#364 Bk offline installation 1.4
  docs/Content/Install_offline.md
Labels: approved, lgtm, size/M

#365 Update Install_offline.md
  docs/Content/Install_offline.md
Labels: approved, lgtm, size/S

#366 update meterdef for bundle
  controllers/resources/service/meter_definition.go
Labels: approved, lgtm, size/XS

#359 Add zen configmap
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensingbindinfo.yaml
  controllers/ibmlicenseservicereporter_controller.go
  controllers/ibmlicensing_controller.go
  controllers/resources/helper.go
  controllers/resources/reporter/secrets.go
  deploy-old/olm-catalog/ibm-licensing-operator/1.5.0/ibm-licensing-operator.v1.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#368 Update Configuration.md
  docs/Content/Configuration.md
Labels: approved, lgtm, size/S

#369 Issue45638
  deploy/operator.yaml
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
Labels: approved, lgtm, size/S

#370 Bk ingress master
  docs/Content/Configuration.md
Labels: approved, lgtm, size/S

#372 Update meter_definition.go
  controllers/resources/service/meter_definition.go
Labels: approved, lgtm, size/XS

#371 move cloning the repository to the beginning
  docs/Content/Install_offline.md
Labels: approved, lgtm, size/S

#373 Update Install_offline.md
  docs/Content/Install_offline.md
Labels: approved, lgtm, size/S

#374 logs fix after rhmp param switch
  controllers/resources/helper.go
Labels: approved, lgtm, size/XS

#376 Update Install_offline.md
  docs/Content/Install_offline.md
Labels: size/S

#375 fix all sed commands and make custom namespace install easier
  docs/Content/Install_offline.md
Labels: approved, lgtm, size/M

#377 Fix install offline doc sed master
  docs/Content/Install_offline.md
Labels: approved, lgtm, size/M

#378 fix replace and channels
  Makefile
  bundle.Dockerfile
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
Labels: approved, size/S

#379 usage flag hidden on OCP UI
  api/v1alpha1/ibmlicensing_types.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#380 fix for usage container lack of rbac
  bundle/manifests/ibm-license-service_rbac.authorization.k8s.io_v1_clusterrole.yaml
  config/rbac/role_operands.yaml
Labels: approved, lgtm, size/S

#381 env variable into container from cr
  api/v1alpha1/ibmlicenseservicereporter_types.go
  api/v1alpha1/ibmlicensing_types.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicenseservicereporters.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  config/crd/bases/operator.ibm.com_ibmlicenseservicereporters.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  controllers/resources/reporter/database.go
  controllers/resources/reporter/helper.go
  controllers/resources/reporter/receiver.go
  controllers/resources/reporter/ui.go
  controllers/resources/service/containers.go
Labels: approved, lgtm, size/L

#382 Delete zen bind info
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensingbindinfo.yaml
  deploy-old/olm-catalog/ibm-licensing-operator/1.5.0/ibm-licensing-operator.v1.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#383 update for reporter env var
  controllers/resources/reporter/helper.go
Labels: approved, size/S

#384 spelling Red Hat
  api/v1alpha1/ibmlicensing_types.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#385 fix replace
  Makefile
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
Labels: approved, size/XS

#386 Create UI only when possible
  controllers/ibmlicenseservicereporter_controller.go
  controllers/ibmlicenseservicereporter_controller_test.go
  controllers/resources/helper.go
  controllers/resources/reporter/deployments.go
  controllers/resources/reporter/ui.go
Labels: approved, lgtm, size/M

#387 Troubleshooting and custom certificate changes
  docs/Content/Configuration.md
  docs/Content/Troubleshooting.md
  docs/License_Service_main.md
Labels: approved, lgtm, size/M

#389 migrate update from 1.4. to master
  controllers/ibmlicensing_controller.go
Labels: approved, lgtm, size/S

#390 Bk doc certificate master
  docs/Content/Configuration.md
  docs/Content/Troubleshooting.md
  docs/License_Service_main.md
Labels: approved, lgtm, size/M

#391 update default channel used in script for ls installation
  Makefile
  common/scripts/ibm_licensing_operator_install.sh
Labels: approved, lgtm, size/S

#392 Update operator.ibm.com_v1alpha1_ibmlicensing.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
Labels: approved, size/XS

#393 ClusterIP service logs fix
  controllers/resources/helper.go
Labels: approved, lgtm, size/XS

#394 Zen bind info
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/config/.golangci.yml
  config/rbac/role.yaml
  controllers/ibmlicenseservicereporter_controller.go
  controllers/resources/helper.go
  controllers/resources/reporter/helper.go
  controllers/resources/reporter/secrets.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, size/L

#395 fix test
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS
