Repository IBM/ibm-licensing-operator, pull requests merged in 2021-08, with the labels that each got.

#436 Linter fixes
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator_v1alpha1_ibmlicensingmetadata.yaml
Labels: approved, lgtm, size/XS

#437 update go to 1.16
  .github/workflows/kind.yml
  .github/workflows/ocp.yml
  CONTRIBUTING.md
  go.mod
Labels: approved, lgtm, size/S

#438 update go to 1.16
  go.mod
Labels: approved, lgtm, size/XS

#440 make bundle
  api/v1alpha1/ibmlicensingmetadata_types.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensingmetadatas.yaml
  config/crd/bases/operator.ibm.com_ibmlicensingmetadatas.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#442 add missing operator image relatedImage
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
Labels: approved, size/XS, lgtm

#444 scorecard kind update
  .github/workflows/kind.yml
Labels: approved, size/XS, lgtm

#446 Zen loc test
  .github/workflows/kind.yml
  .github/workflows/ocp.yml
  CONTRIBUTING.md
  Dockerfile
  Makefile
  api/v1alpha1/ibmlicensingmetadata_types.go
  bundle/manifests/operator.ibm.com_ibmlicensingmetadatas.yaml
  config/crd/bases/operator.ibm.com_ibmlicensingmetadatas.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator_v1alpha1_ibmlicensingmetadata.yaml
  controllers/ibmlicenseservicereporter_controller.go
  controllers/ibmlicensing_controller.go
  controllers/resources/helper.go
  controllers/resources/reporter/routing.go
  controllers/resources/reporter/ui.go
  controllers/resources/reporter/volumes.go
  go.mod
Labels: approved, size/L

#448 1.7 doc updates
  README.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
  docs/Content/Troubleshooting.md
  docs/License_Service_main.md
Labels: approved, lgtm, size/S

#449 Fix kind tests
  .github/workflows/kind.yml
Labels: approved, lgtm, size/S

#447 Update 1.8.0
  Makefile
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  docs/Content/Troubleshooting.md
  version/version.go
Labels: approved, lgtm, size/M

#451 UBI update automation
  Dockerfile
  base_images.json
  common/config/.hadolint.yml
  common/scripts/config_docker.sh
Labels: approved, size/XS, lgtm

#452 Redhat support user workload prometh
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/ibmlicensing_controller.go
  controllers/resources/helper.go
  controllers/resources/service/helper.go
  controllers/resources/service/networking.go
  controllers/resources/service/service_monitor.go
Labels: approved, lgtm, size/L

#453 Ubi update automation
  Makefile
Labels: approved, size/XS, lgtm

#454 add cluster permissions
  docs/Content/Preparing_for_installation.md
  docs/License_Service_main.md
Labels: approved, size/S

#461 fixed env vars comparison for containers
  controllers/resources/deployments.go
Labels: approved, lgtm, size/S

#464 update go version to 1.17
  .github/workflows/kind.yml
  .github/workflows/ocp.yml
  CONTRIBUTING.md
  go.mod
Labels: approved, lgtm, size/M

#463 update go version to 1.17
  .github/workflows/kind.yml
  go.mod
  go.sum
Labels: approved, lgtm, size/L
