Repository IBM/ibm-licensing-operator, pull requests merged in 2022-06, with the labels that each got.

#623 Bk 1.16 updates
  README.md
  docs/Content/Configuration.md
  docs/Content/Install_from_scratch.md
  docs/Content/Retrieving_data.md
  docs/Content/Uninstalling.md
  docs/Content/Whats_new.md
Labels: approved, lgtm, size/L

#625 Remove env secret
  controllers/resources/reporter/database.go
  controllers/resources/reporter/helper.go
  controllers/resources/reporter/receiver.go
  controllers/resources/reporter/volumes.go
Labels: lgtm, size/M

#626 Remove env var secret ltsr
  controllers/resources/reporter/database.go
  controllers/resources/reporter/helper.go
  controllers/resources/reporter/receiver.go
  controllers/resources/reporter/volumes.go
Labels: approved, lgtm, size/M
