Repository IBM/ibm-licensing-operator, pull requests merged in 2022-03, with the labels that each got.

#581 update version in documentation + fix IBM Docs links
  docs/Content/Backup_and_upgrade.md
  docs/License_Service_main.md
Labels: approved, size/XS, lgtm

#583 improve docs by deleting spaces
  docs/Content/Backup_and_upgrade.md
Labels: approved, size/XS, lgtm

#582 improve docs by deleting spaces and unnecessary line
  docs/Content/Backup_and_upgrade.md
Labels: approved, size/XS, lgtm

#586 fix latest version after 1.9.0
  docs/Content/Install_offline.md
  docs/Content/Uninstalling.md
Labels: approved, size/XS, lgtm

#585 fix latest version after 1.9.0
  docs/Content/Install_offline.md
  docs/Content/Uninstalling.md
Labels: approved, size/XS, lgtm

#584 Update 1.14
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
  version/version.go
Labels: approved, lgtm, size/M

#587 add quiet err command
  common/scripts/ibm_licensing_operator_install.sh
Labels: approved, size/XS, lgtm

#588 add date to verbose installation of olm, remove olm wrong version log
  common/scripts/ibm_licensing_operator_install.sh
Labels: approved, lgtm, size/M

#589 improve ingress configuration info in docs
  docs/Content/Configuration.md
Labels: approved, size/M

#590 Fix make check
  api/v1/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.deepcopy.go
Labels: approved, size/XS, lgtm

#591 remove operator from display name
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
Labels: approved, size/XS, lgtm

#592 Bk doc update 16 march
  docs/Content/Retrieving_data.md
  docs/License_Service_main.md
Labels: approved, lgtm, size/S

#595 minor updates
  docs/Content/Retrieving_data.md
  docs/License_Service_main.md
Labels: approved, size/XS, lgtm

#596 fixed uninstall doc
  docs/Content/Backup_and_upgrade.md
  docs/Content/Uninstalling.md
Labels: approved, lgtm, size/M
