Repository IBM/ibm-licensing-operator, pull requests merged in 2022-11, with the labels that each got.

#689 make zen nginx have correct ls namespace
  controllers/resources/reporter/secrets.go
Labels: approved, size/XS, lgtm

#691 fix fips not possible to update tls in route
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/ibmlicensing_controller.go
Labels: approved, size/S

#694 Update-1.16.6
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: approved, lgtm, size/M

#695 Updated next_csv script for version update
  common/scripts/next_csv.sh
Labels: approved, lgtm, size/M

#681 FIPS compliance for License Service
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/ibmlicensing_controller.go
  controllers/resources/helper.go
  controllers/resources/service/containers.go
  controllers/resources/service/helper.go
  controllers/resources/service/routing.go
  controllers/resources/service/volumes.go
Labels: approved, lgtm, size/L

#696 Fips compliance lsr
  controllers/ibmlicenseservicereporter_controller.go
  controllers/resources/reporter/helper.go
  controllers/resources/reporter/routing.go
  controllers/resources/reporter/volumes.go
Labels: approved, lgtm, size/L

#700 New prow cluster name
  common/Makefile.common.mk
Labels: size/XS

#703 New prow cluster name
  common/Makefile.common.mk
Labels: size/XS

#704 New prow cluster name
  common/Makefile.common.mk
Labels: size/XS

#699 Update linters
  CONTRIBUTING.md
  Dockerfile
  Makefile
  api/v1/groupversion_info.go
  api/v1/ibmlicensingdefinition_types.go
  api/v1/ibmlicensingquerysource_types.go
  api/v1alpha1/features/zz_generated.deepcopy.go
  api/v1alpha1/ibmlicensingmetadata_types.go
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/.yamllint.yml
  common/scripts/install-linters-development.sh
  common/scripts/lint_go.sh
  common/scripts/multiarch_image.sh
  controllers/ibmlicenseservicereporter_controller.go
  controllers/ibmlicensing_controller.go
  main.go
  version/version.go
Labels: approved, lgtm, size/L

#706 Update to version 1.20.0
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: approved, lgtm, size/M
