Repository IBM/ibm-licensing-operator, pull requests merged in 2022-09, with the labels that each got.

#667 unify module paths to match git repo paths -> 'ibm' to 'IBM'
  Makefile
  api/v1alpha1/features.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/scripts/lint_copyright_banner.sh
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  controllers/ibmlicenseservicereporter_controller.go
  controllers/ibmlicenseservicereporter_controller_test.go
  controllers/ibmlicensing_controller.go
  controllers/ibmlicensing_controller_test.go
  controllers/resources/containers.go
  controllers/resources/helper.go
  controllers/resources/reporter/database.go
  controllers/resources/reporter/deployments.go
  controllers/resources/reporter/helper.go
  controllers/resources/reporter/pvc.go
  controllers/resources/reporter/rbac.go
  controllers/resources/reporter/receiver.go
  controllers/resources/reporter/routing.go
  controllers/resources/reporter/secrets.go
  controllers/resources/reporter/services.go
  controllers/resources/reporter/ui.go
  controllers/resources/reporter/volumes.go
  controllers/resources/service/containers.go
  controllers/resources/service/deployments.go
  controllers/resources/service/helper.go
  controllers/resources/service/meter_definition.go
  controllers/resources/service/networking.go
  controllers/resources/service/routing.go
  controllers/resources/service/secrets.go
  controllers/resources/service/service_monitor.go
  controllers/resources/service/services.go
  controllers/resources/service/volumes.go
  controllers/suite_test.go
  deploy-old/olm-catalog/ibm-licensing-operator/1.1.0/ibm-licensing-operator.v1.1.0.clusterserviceversion.yaml
  deploy-old/olm-catalog/ibm-licensing-operator/1.1.1/ibm-licensing-operator.v1.1.1.clusterserviceversion.yaml
  deploy-old/olm-catalog/ibm-licensing-operator/1.1.2/ibm-licensing-operator.v1.1.2.clusterserviceversion.yaml
  deploy-old/olm-catalog/ibm-licensing-operator/1.1.3/ibm-licensing-operator.v1.1.3.clusterserviceversion.yaml
  deploy-old/olm-catalog/ibm-licensing-operator/1.2.0/ibm-licensing-operator.v1.2.0.clusterserviceversion.yaml
  deploy-old/olm-catalog/ibm-licensing-operator/1.2.1/ibm-licensing-operator.v1.2.1.clusterserviceversion.yaml
  deploy-old/olm-catalog/ibm-licensing-operator/1.2.2/ibm-licensing-operator.v1.2.2.clusterserviceversion.yaml
  deploy-old/olm-catalog/ibm-licensing-operator/1.2.3/ibm-licensing-operator.v1.2.3.clusterserviceversion.yaml
  deploy-old/olm-catalog/ibm-licensing-operator/1.3.0/ibm-licensing-operator.v1.3.0.clusterserviceversion.yaml
  deploy-old/olm-catalog/ibm-licensing-operator/1.3.1/ibm-licensing-operator.v1.3.1.clusterserviceversion.yaml
  deploy-old/olm-catalog/ibm-licensing-operator/1.4.0/ibm-licensing-operator.v1.4.0.clusterserviceversion.yaml
  deploy-old/olm-catalog/ibm-licensing-operator/1.4.1/ibm-licensing-operator.v1.4.1.clusterserviceversion.yaml
  deploy-old/olm-catalog/ibm-licensing-operator/1.5.0/ibm-licensing-operator.v1.5.0.clusterserviceversion.yaml
  go.mod
  main.go
Labels: approved, lgtm, size/L

#665 Added additional roles for operator to enable deployment request.
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/rbac/role_operands.yaml
Labels: approved, size/S

#668 Updated to version 1.16.4
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: approved, lgtm, size/M
