Repository IBM/ibm-licensing-operator, pull requests merged in 2022-12, with the labels that each got.

#702 Fips ltsr
  .gitignore
  README.md
  api/v1alpha1/helper.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/ibmlicensing_controller.go
  controllers/resources/deployments.go
  controllers/resources/helper.go
  controllers/resources/reporter/helper.go
  controllers/resources/reporter/receiver.go
  controllers/resources/reporter/volumes.go
  controllers/resources/service/containers.go
  controllers/resources/service/helper.go
  controllers/resources/service/routing.go
  controllers/resources/service/secrets.go
  controllers/resources/service/services.go
  controllers/resources/service/volumes.go
Labels: approved, size/XL

#707 Fips compliance lsr (#696)
  controllers/ibmlicenseservicereporter_controller.go
  controllers/resources/reporter/helper.go
  controllers/resources/reporter/routing.go
  controllers/resources/reporter/volumes.go
Labels: approved, lgtm, size/L

#710 Removed redundant quotes from REGISTRY variable
  Makefile
Labels: size/XS, lgtm

#708 Extend Checking IBMLicensing instance status time for overloaded clus…
  common/scripts/ibm_licensing_operator_install.sh
Labels: approved, size/XS, lgtm

#715 certificate hardening (#702)
  .gitignore
  api/v1alpha1/helper.go
  controllers/ibmlicensing_controller.go
  controllers/resources/deployments.go
  controllers/resources/helper.go
  controllers/resources/reporter/helper.go
  controllers/resources/reporter/receiver.go
  controllers/resources/reporter/volumes.go
  controllers/resources/service/containers.go
  controllers/resources/service/helper.go
  controllers/resources/service/secrets.go
  controllers/resources/service/services.go
  controllers/resources/service/volumes.go
Labels: approved, size/L

#713 Added auto detection of current channel
  Makefile
  bundle/metadata/annotations.yaml
Labels: approved, lgtm, size/M

#718 Fix certificate rotation
  controllers/ibmlicenseservicereporter_controller.go
  controllers/ibmlicensing_controller.go
Labels: approved, size/XS

#717 Fix cert rotation
  controllers/ibmlicenseservicereporter_controller.go
  controllers/ibmlicensing_controller.go
Labels: approved, size/XS

#724 fix comparison of deployments
  controllers/resources/deployments.go
Labels: approved, size/XS

#720 fix cert rotation logic
  controllers/ibmlicenseservicereporter_controller.go
  controllers/ibmlicensing_controller.go
Labels: approved, size/XS

#721 fix cert rotation logic
  controllers/ibmlicenseservicereporter_controller.go
  controllers/ibmlicensing_controller.go
Labels: approved, size/XS

#726 rename configmap field
  controllers/resources/service/secrets.go
Labels: approved, size/XS

#725 rename configmap field
  controllers/resources/service/secrets.go
Labels: approved, size/XS

#727 Fix docker tag multiarch
  common/scripts/multiarch_image.sh
Labels: approved, size/XS, lgtm
