Repository IBM/ibm-licensing-operator, pull requests merged in 2022-10, with the labels that each got.

#675 Updated to version 1.16.5
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: approved, size/M

#676 Double counting implementation port on LTSR
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/rbac/role_operands.yaml
Labels: approved, size/S

#678 Reconciliation loop ingress removal fix
  controllers/ibmlicensing_controller.go
Labels: approved, lgtm, size/S

#679 unify productID annotation name in case of licensing query source crd
  config/samples/operator_v1_ibmlicensingquerysource.yaml
Labels: approved, size/XS, lgtm

#684 Fixed next_csv.sh script for version bump
  common/scripts/next_csv.sh
Labels: approved, lgtm, size/M

#686 Fixed TLS-log-output when reconciling
  controllers/resources/helper.go
Labels: approved, lgtm, size/S

#685 Reconciliation loop ingress removal fix
  controllers/ibmlicensing_controller.go
Labels: approved, size/S

#687 [LTSR] Fixed TLS-log-output when reconciling
  controllers/resources/helper.go
Labels: approved, lgtm, size/S
