Repository IBM/ibm-licensing-operator, pull requests merged in 2022-02, with the labels that each got.

#550 Update catalog source (#547)
  common/config/.hadolint.yml
  common/scripts/ibm_licensing_operator_install.sh
  docs/Content/Install_from_scratch.md
  docs/Content/Install_on_OCP.md
Labels: approved, size/XS, lgtm

#551 Bk doc updates 3.15 to master
  README.md
  docs/Content/Automatic_installation.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_on_OCP.md
  docs/Content/Install_without_OLM.md
Labels: approved, lgtm, size/M

#553 update 1.13
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
  version/version.go
Labels: approved, lgtm, size/M

#556 Revert "update 1.13"
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
  version/version.go
Labels: approved, lgtm, size/M

#557 Update 1.13
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
  version/version.go
Labels: approved, lgtm, size/M

#562 update ls resource limits
  api/v1alpha1/helper.go
Labels: approved, lgtm, size/S

#565 Ls resource limits update latest
  docs/Content/Preparing_for_installation.md
Labels: approved, lgtm, size/S

#563 update doc for standalone LS resource limits
  docs/Content/Preparing_for_installation.md
Labels: approved, lgtm, size/S

#564 Update default resources to CS x86 medium profile
  api/v1alpha1/helper.go
Labels: approved, size/XS, lgtm

#560 Add 1.11 upgrade procedure
  docs/Content/Backup_and_upgrade.md
  docs/Content/Retrieving_data.md
  docs/Content/Upgrading_to_111x.md
  docs/License_Service_main.md
Labels: approved, lgtm, size/M

#568 update notes in install procedure
  README.md
  docs/Content/Automatic_installation.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_on_OCP.md
  docs/Content/Install_without_OLM.md
  docs/Content/Installation_scenarios.md
Labels: approved, lgtm, size/S

#569 update a note in readme
  README.md
Labels: approved, size/XS, lgtm

#571 Trigger build run with go 1.17.7
  README.md
Labels: approved, size/XS, lgtm

#567 Fix iks installation path latest
  README.md
  common/scripts/ibm_licensing_operator_install.sh
  docs/Content/Automatic_installation.md
  docs/Content/Backup_and_upgrade.md
  docs/Content/Configuration.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_on_OCP.md
  docs/Content/Install_without_OLM.md
  docs/Content/Installation_scenarios.md
  docs/Content/Preparing_for_installation.md
  docs/Content/Upgrading_to_111x.md
  docs/Content/Upgrading_to_14x.md
  docs/License_Service_main.md
Labels: approved, size/XL

#559 Fix iks installation path
  README.md
  api/v1alpha1/helper.go
  common/scripts/ibm_licensing_operator_install.sh
  docs/Content/Automatic_installation.md
  docs/Content/Backup_and_upgrade.md
  docs/Content/Configuration.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_on_OCP.md
  docs/Content/Install_without_OLM.md
  docs/Content/Installation_scenarios.md
  docs/Content/Preparing_for_installation.md
  docs/Content/Retrieving_data.md
  docs/Content/Upgrading_to_14x.md
  docs/License_Service_main.md
Labels: approved, size/XL

#572 IBM Licensing Definition
  Makefile
  PROJECT
  api/v1/groupversion_info.go
  api/v1/ibmlicensingdefinition_types.go
  api/v1/zz_generated.deepcopy.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensingdefinitions.yaml
  config/crd/bases/operator.ibm.com_ibmlicensingdefinitions.yaml
  config/crd/kustomization.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/rbac/role_operands.yaml
  config/samples/operator_v1_ibmlicensingdefinition.yaml
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
  main.go
Labels: approved, lgtm, size/XL

#573 fix operatorgroup check
  common/scripts/ibm_licensing_operator_install.sh
Labels: approved, size/XS, lgtm

#574 fix operatorgroup check
  common/scripts/ibm_licensing_operator_install.sh
Labels: approved, size/XS, lgtm

#576 fix OLM version
  common/scripts/ibm_licensing_operator_install.sh
Labels: approved, size/XS, lgtm

#578 Bk uninstall doc update latest
  docs/Content/Uninstalling.md
  docs/License_Service_main.md
Labels: size/XS

#577 Update Uninstalling.md
  docs/Content/Uninstalling.md
  docs/License_Service_main.md
Labels: size/XS
