Repository IBM/ibm-licensing-operator, pull requests merged in 2022-04, with the labels that each got.

#601 update License Service documentation on GitHub
  docs/Content/Install_from_scratch.md
  docs/Content/Install_on_OCP.md
  docs/Content/Optional_features.md
  docs/Content/Troubleshooting.md
  docs/Content/Uninstalling.md
  docs/Content/Whats_new.md
  docs/License_Service_main.md
  images/installed.png
  images/ocp_create_instance.png
  images/operator-hub-licensing.png
Labels: approved, size/L

#600 Update 1.15
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
  version/version.go
Labels: approved, lgtm, size/M

#599 Bump golang.org/x/net and crypto
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#598 Bump golang.org/x/crypto
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#602 Replace deprecated K8S API beta.kubernetes.io/arch
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/resources/reporter/deployments.go
  controllers/resources/service/deployments.go
Labels: approved, size/XS, lgtm

#604 update golint version in contributing and remove linting test files
  CONTRIBUTING.md
  common/Makefile.common.mk
  common/config/.golangci.yml
Labels: approved, size/XS, lgtm

#603 display go version on build
  common/scripts/catalog/Dockerfile
  common/scripts/gobuild.sh
Labels: approved, size/XS, lgtm

#605 Replace quay.io to icr.io
  .github/workflows/kind.yml
  Makefile
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/scripts/catalog_build.sh
  common/scripts/get-image-sha.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  deploy-old/operator.yaml
  docs/Content/Install_offline.md
  docs/Content/Uninstalling.md
Labels: approved, size/M
