Repository IBM/ibm-licensing-operator, pull requests merged in 2022-01, with the labels that each got.

#538 Use checkboxes instead of text fields where possible
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#539 Hide rhmp input field
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
Labels: approved, size/XS, lgtm

#540 Bump eus go version
  README.md
Labels: approved, size/XS, lgtm

#542 Adding information about profiles to required resources page
  docs/Content/Configuration.md
  docs/Content/Preparing_for_installation.md
Labels: approved, lgtm, size/S

#543 Adding information about profiles to required resources page
  docs/Content/Configuration.md
  docs/Content/Preparing_for_installation.md
Labels: approved, lgtm, size/S

#545 fixing the table with profiles
  docs/Content/Preparing_for_installation.md
Labels: approved, size/XS, lgtm

#541 add services meter def
  controllers/resources/service/meter_definition.go
Labels: approved, lgtm, size/M

#548 Integrate controller-filtered-cache & run GC
  controllers/ibmlicenseservicereporter_controller.go
  controllers/ibmlicensing_controller.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, size/L
