Repository IBM/ibm-licensing-operator, pull requests merged in 2022-05, with the labels that each got.

#597 add licensingquerysource crd
  Makefile
  PROJECT
  api/v1/ibmlicensingquerysource_types.go
  api/v1/zz_generated.deepcopy.go
  api/v1alpha1/features.go
  api/v1alpha1/features/prometheus_query_source.go
  api/v1alpha1/features/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensingquerysources.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  config/crd/bases/operator.ibm.com_ibmlicensingquerysources.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  config/crd/kustomization.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/rbac/role_operands.yaml
  config/samples/operator_v1_ibmlicensingquerysource.yaml
  controllers/resources/service/containers.go
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
Labels: approved, lgtm, size/XL

#607 documentation updates
  docs/Content/Automatic_installation.md
  docs/Content/Backup_and_upgrade.md
  docs/Content/Configuration.md
  docs/Content/Install_without_OLM.md
  docs/Content/Uninstalling.md
  docs/Content/Whats_new.md
Labels: approved, lgtm, size/M

#611 Update to 1.16 version
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
  version/version.go
Labels: approved, lgtm, size/M

#613 Revert "Update to 1.16 version"
  Makefile
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
  version/version.go
Labels: approved, lgtm, size/M

#614 Update to 1.16
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
  version/version.go
Labels: approved, lgtm, size/M

#616 Add /services_adoption endpoint to default reader role
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/rbac/role_operands.yaml
Labels: approved, size/XS, lgtm

#617 fixing the offline installation typo
  docs/Content/Automatic_installation.md
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
Labels: approved, size/XS, lgtm

#618 fixing the offline installation typo
  docs/Content/Automatic_installation.md
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
Labels: approved, size/XS, lgtm

#621 updates basing on Marta's review - move to master
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
  docs/Content/Retrieving_data.md
Labels: approved, lgtm, size/S

#608 fix readme quay.io replace that should replace icr.io
  docs/Content/Install_offline.md
  docs/Content/Install_on_OCP.md
Labels: approved, size/XS

#622 Revert "Add /services_adoption endpoint to default reader role (#616)"
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/rbac/role_operands.yaml
Labels: approved, size/XS, lgtm
