Repository IBM/ibm-licensing-operator, pull requests merged in 2022-08, with the labels that each got.

#651 cherry-pick: configuration_update
  docs/Content/Configuration.md
Labels: approved, size/XS, lgtm

#653 Update OWNERS
  OWNERS
Labels: approved, size/XS, lgtm

#644 Update OWNERS ltsr
  OWNERS
Labels: approved, size/XS, lgtm

#654 Update 1.16.3
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
  version/version.go
Labels: approved, size/M

#659 Remove documentation for 1.16 - CD and first LTSR
  README.md
  docs/Content/Automatic_installation.md
  docs/Content/Backup_and_upgrade.md
  docs/Content/Configuration.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_on_OCP.md
  docs/Content/Install_without_OLM.md
  docs/Content/Installation_scenarios.md
  docs/Content/Optional_features.md
  docs/Content/Preparing_for_installation.md
  docs/Content/Retrieving_data.md
  docs/Content/Troubleshooting.md
  docs/Content/Uninstalling.md
  docs/Content/Whats_new.md
  docs/License_Service_main.md
Labels: approved, size/XXL

#660 Remove documentation for 1.16.1 - LTSR
  README.md
  docs/Content/Automatic_installation.md
  docs/Content/Backup_and_upgrade.md
  docs/Content/Configuration.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_on_OCP.md
  docs/Content/Install_without_OLM.md
  docs/Content/Installation_scenarios.md
  docs/Content/Optional_features.md
  docs/Content/Preparing_for_installation.md
  docs/Content/Retrieving_data.md
  docs/Content/Troubleshooting.md
  docs/Content/Uninstalling.md
  docs/Content/Whats_new.md
  docs/License_Service_main.md
Labels: approved, size/XXL

#661 Remove documentation for 1.16.2 - LTSR
  README.md
  docs/Content/Automatic_installation.md
  docs/Content/Backup_and_upgrade.md
  docs/Content/Configuration.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_on_OCP.md
  docs/Content/Install_without_OLM.md
  docs/Content/Installation_scenarios.md
  docs/Content/Optional_features.md
  docs/Content/Preparing_for_installation.md
  docs/Content/Retrieving_data.md
  docs/Content/Troubleshooting.md
  docs/Content/Uninstalling.md
  docs/Content/Whats_new.md
  docs/License_Service_main.md
Labels: approved, size/XXL

#662 Remove documentation for master
  README.md
  docs/Content/Automatic_installation.md
  docs/Content/Backup_and_upgrade.md
  docs/Content/Configuration.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_on_OCP.md
  docs/Content/Install_without_OLM.md
  docs/Content/Installation_scenarios.md
  docs/Content/Optional_features.md
  docs/Content/Preparing_for_installation.md
  docs/Content/Retrieving_data.md
  docs/Content/Troubleshooting.md
  docs/Content/Uninstalling.md
  docs/Content/Whats_new.md
  docs/License_Service_main.md
Labels: approved, size/XXL

#664 Remove documentation for 1.17
  README.md
  docs/Content/Automatic_installation.md
  docs/Content/Backup_and_upgrade.md
  docs/Content/Configuration.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_on_OCP.md
  docs/Content/Install_without_OLM.md
  docs/Content/Installation_scenarios.md
  docs/Content/Optional_features.md
  docs/Content/Preparing_for_installation.md
  docs/Content/Retrieving_data.md
  docs/Content/Troubleshooting.md
  docs/Content/Uninstalling.md
  docs/Content/Whats_new.md
  docs/License_Service_main.md
Labels: approved, size/XXL
