Repository IBM/ibm-licensing-operator, pull requests merged in 2022-07, with the labels that each got.

#628 Increase LSR route timeout to 90s
  controllers/resources/reporter/routing.go
Labels: approved, lgtm, size/S

#630 Provide forward and backwards compatibility
  api/v1/ibmlicensingdefinition_types.go
  api/v1/ibmlicensingquerysource_types.go
  api/v1alpha1/ibmlicenseservicereporter_types.go
  api/v1alpha1/ibmlicensing_types.go
  api/v1alpha1/ibmlicensingmetadata_types.go
  bundle/manifests/operator.ibm.com_ibmlicenseservicereporters.yaml
  bundle/manifests/operator.ibm.com_ibmlicensingdefinitions.yaml
  bundle/manifests/operator.ibm.com_ibmlicensingmetadatas.yaml
  bundle/manifests/operator.ibm.com_ibmlicensingquerysources.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  config/crd/bases/operator.ibm.com_ibmlicenseservicereporters.yaml
  config/crd/bases/operator.ibm.com_ibmlicensingdefinitions.yaml
  config/crd/bases/operator.ibm.com_ibmlicensingmetadatas.yaml
  config/crd/bases/operator.ibm.com_ibmlicensingquerysources.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
Labels: approved, lgtm, size/S

#629 documentation updates for Tanzu
  Makefile
  docs/Content/Configuration.md
  docs/Content/Preparing_for_installation.md
  docs/Content/Whats_new.md
  docs/License_Service_main.md
Labels: approved, lgtm, size/M

#637 updates for Tanzu
  Makefile
  docs/Content/Configuration.md
  docs/Content/Preparing_for_installation.md
  docs/Content/Whats_new.md
  docs/License_Service_main.md
Labels: approved, lgtm, size/M

#636 Update 1.16.1
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
  version/version.go
Labels: approved, size/M

#635 Ltsr doc update 220719
  docs/Content/Configuration.md
  docs/Content/Retrieving_data.md
  docs/Content/Uninstalling.md
Labels: approved, lgtm, size/L

#638 update to version 1.16.2
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
  version/version.go
Labels: approved, lgtm, size/M

#634 Update 1.18
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  docs/Content/Configuration.md
  docs/Content/Install_from_scratch.md
  docs/Content/Install_offline.md
  docs/Content/Install_without_OLM.md
  docs/Content/Preparing_for_installation.md
  docs/Content/Whats_new.md
  docs/License_Service_main.md
  version/version.go
Labels: approved, lgtm, size/L

#642 Fix logging in automatic install with OLM - LTSR
  common/scripts/ibm_licensing_operator_install.sh
Labels: approved, lgtm, size/S

#641 Fix logging in automatic install with OLM
  common/scripts/ibm_licensing_operator_install.sh
Labels: approved, lgtm, size/S

#645 enable internal ltsr catalog for devops
  Makefile
Labels: approved, lgtm, size/S

#640 enable internal catalog streams for devops
  Makefile
Labels: approved, lgtm, size/S

#646 fix too fast sub recreation and wrong echo
  common/scripts/ibm_licensing_operator_install.sh
Labels: approved, lgtm, size/S

#647 fix too fast sub recreation and wrong echo
  common/scripts/ibm_licensing_operator_install.sh
Labels: approved, lgtm, size/S

#649 get current git branch name
  Makefile
Labels: approved, size/XS, lgtm

#650 get current git branch name ltsr
  Makefile
Labels: approved, size/XS, lgtm
