Repository IBM/ibm-licensing-operator, pull requests merged in 2023-01, with the labels that each got.

#730 Make the operand file system read-only
  controllers/resources/containers.go
  controllers/resources/reporter/receiver.go
  controllers/resources/reporter/volumes.go
  controllers/resources/service/volumes.go
Labels: approved, lgtm, size/M

#731 Make the operand file system read-only - ltsr
  controllers/resources/containers.go
  controllers/resources/reporter/receiver.go
  controllers/resources/reporter/volumes.go
  controllers/resources/service/volumes.go
Labels: approved, lgtm, size/M

#716 Fix multiple instances CRs
  api/v1alpha1/ibmlicensing_types.go
  bundle.Dockerfile
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  controllers/ibmlicensing_controller.go
  controllers/resources/service/helper.go
Labels: approved, size/M

#733 Update to version 1.16.7
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: size/M

#722 Client go update
  .github/workflows/ci.yml
  .github/workflows/kind.yml
  controllers/ibmlicenseservicereporter_controller.go
  controllers/ibmlicensing_controller.go
  controllers/resources/containers.go
  controllers/resources/helper.go
  controllers/resources/reporter/database.go
  controllers/resources/reporter/receiver.go
  controllers/resources/reporter/ui.go
  controllers/resources/service/containers.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, size/XL

#736 update client-go and other dependencies
  .github/workflows/ci.yml
  .github/workflows/kind.yml
  Dockerfile
  api/v1/groupversion_info.go
  api/v1/ibmlicensingdefinition_types.go
  api/v1/ibmlicensingquerysource_types.go
  api/v1alpha1/ibmlicensingmetadata_types.go
  common/config/.yamllint.yml
  common/scripts/lint_go.sh
  controllers/ibmlicenseservicereporter_controller.go
  controllers/ibmlicensing_controller.go
  controllers/resources/containers.go
  controllers/resources/helper.go
  controllers/resources/reporter/database.go
  controllers/resources/reporter/receiver.go
  controllers/resources/reporter/ui.go
  controllers/resources/service/containers.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
  version/version.go
Labels: approved, lgtm, size/XL

#738 update go-restful to address CVE
  go.mod
  go.sum
Labels: approved, size/XS, lgtm

#737 add default reader token to support k8s 1.24+
  controllers/ibmlicensing_controller.go
  controllers/resources/service/helper.go
  controllers/resources/service/secrets.go
Labels: approved, lgtm, size/M

#714 change configmap in which certificates are inserted
  controllers/ibmlicensing_controller.go
  controllers/resources/service/secrets.go
Labels: approved, size/S

#734 Port fix multiple cr instances to ltsr
  api/v1alpha1/ibmlicensing_types.go
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  controllers/ibmlicensing_controller.go
  controllers/resources/service/helper.go
Labels: size/M

#742 update go-restful
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#747 Updated registry endpoint
  Dockerfile
  Makefile
  common/Makefile.common.mk
  common/config/.hadolint.yml
  common/scripts/config_docker.sh
  common/scripts/config_docker_scratch.sh
Labels: approved, lgtm, size/M

#744 Update to version 1.20.1
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/relatedImages.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: approved, size/M

#743 Upadated docker registry endpoints [CD]
  .github/workflows/kind.yml
  Dockerfile
  Makefile
  common/Makefile.common.mk
  common/config/.hadolint.yml
  common/scripts/config_docker.sh
  common/scripts/config_docker_scratch.sh
Labels: approved, lgtm, size/M

#745 move deployment reconcilation later
  controllers/ibmlicensing_controller.go
Labels: approved, lgtm, size/S

#741 add default reader token to support k8s 1.24+
  controllers/ibmlicensing_controller.go
  controllers/resources/service/helper.go
  controllers/resources/service/secrets.go
Labels: approved, lgtm, size/M

#732 Removed unused test target/fix linting
  .github/workflows/kind.yml
  CONTRIBUTING.md
  Makefile
  common/Makefile.common.mk
  common/scripts/install-linters-development.sh
Labels: approved, size/L
