Repository IBM/ibm-licensing-operator, pull requests merged in 2023-03, with the labels that each got.

#761 Update to version 1.20.2
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/relatedImages.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: approved, size/M

#763 Trigger new build
  .github/workflows/kind.yml
  Makefile
Labels: approved, size/S

#765 Port new env var names
  .github/workflows/kind.yml
  Makefile
Labels: approved, size/S

#768 fix 2 operand pods after creating the LS instance on IKS
  controllers/ibmlicensing_controller.go
Labels: approved, size/XS, lgtm

#771 fix 2 operand pods after creating the LS instance on IKS
  controllers/ibmlicensing_controller.go
Labels: approved, size/XS, lgtm

#772 Update go-restful to v3.10.1
  go.mod
Labels: approved, size/XS, lgtm

#773 Upgrade /x/net to v0.7.0
  go.mod
  go.sum
Labels: approved, size/S

#774 LS without LSR - fixes
  .gitignore
  bundle/metadata/annotations.yaml
  controllers/suite_test.go
Labels: approved, lgtm, size/S

#767 Auto extend operatorgroup
  .github/workflows/ci.yml
  .github/workflows/kind.yml
  CONTRIBUTING.md
  Makefile
  bundle.Dockerfile
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensingdefinitions.yaml
  bundle/manifests/operator.ibm.com_ibmlicensingmetadatas.yaml
  bundle/manifests/operator.ibm.com_ibmlicensingquerysources.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  bundle/metadata/annotations.yaml
  common/config/.golangci.yml
  common/scripts/ibm_licensing_operator_install.sh
  common/scripts/install-linters-development.sh
  common/scripts/tests/.osdk-scorecard.yaml
  config/crd/bases/operator.ibm.com_ibmlicensingdefinitions.yaml
  config/crd/bases/operator.ibm.com_ibmlicensingmetadatas.yaml
  config/crd/bases/operator.ibm.com_ibmlicensingquerysources.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  config/default/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/role_operands.yaml
  config/rbac/service_account.yaml
  controllers/ibmlicensing_controller.go
  controllers/operandrequest_controller.go
  controllers/operandrequest_controller_test.go
  controllers/operandrequest_discovery.go
  controllers/resources/crds.go
  controllers/resources/envs_test.go
  controllers/resources/helper.go
  controllers/resources/operandrequests.go
  controllers/resources/operatorgroups.go
  controllers/resources/operatorgroups_test.go
  controllers/resources/service/meter_definition.go
  controllers/resources/testutil.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, size/XXL
