Repository IBM/ibm-licensing-operator, pull requests merged in 2023-07, with the labels that each got.

#812 LS CSV description needs update
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#814 Update to version 1.20.6
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/relatedImages.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: lgtm, size/M

#816 update OWNERS
  OWNERS
Labels: approved, size/XS, lgtm

#815 update OWNERS
  OWNERS
Labels: approved, size/XS, lgtm

#817 Remediate CVE-2022-3172
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#818 Disable certificate creation when route is not enabled
  controllers/ibmlicensing_controller.go
  controllers/resources/service/routing.go
  go.mod
  go.sum
Labels: approved, size/M

#819 Fix routeEnabled functionality producing error
  controllers/ibmlicensing_controller.go
  controllers/resources/service/routing.go
  go.mod
  go.sum
Labels: approved, size/M

#813 CSV supported version update
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
Labels: approved, size/XS, lgtm
