Repository IBM/ibm-licensing-operator, pull requests merged in 2023-02, with the labels that each got.

#739 Fix reconcile when no service monitors
  controllers/ibmlicensing_controller.go
Labels: approved, size/XS, lgtm

#750 Fix reconcile when no service monitors - future
  controllers/ibmlicensing_controller.go
Labels: approved, size/XS, lgtm

#749 Recommended namespace
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicenseservicereporters.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_ibmlicenseservicereporters.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/L

#748 add more verbose and clear logging for which instance is active
  .by-cicd
  controllers/ibmlicensing_controller.go
Labels: approved, lgtm, size/S

#753 Delete cluster roles and rolebindings from CSV config
  api/v1alpha1/ibmlicensing_types.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/ibmlicensing_controller.go
Labels: approved, lgtm, size/S

#754 Update channels on rebased ltsr
  Makefile
  bundle/metadata/annotations.yaml
Labels: approved, size/XS, lgtm

#756 Updated explicitly version of the github.com/emicklei/go-restful/v3 d…
  go.mod
Labels: approved, size/XS, lgtm

#751 Cp3 og
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  controllers/resources/envs.go
  controllers/resources/helper.go
  controllers/resources/service/containers.go
  controllers/resources/service/helper.go
  main.go
Labels: approved, lgtm, size/L

#758 add more verbose and clear logging for which instance is active
  controllers/ibmlicensing_controller.go
Labels: approved, lgtm, size/S
