Repository IBM/ibm-licensing-operator, pull requests merged in 2023-09, with the labels that each got.

#824 Olm version update to v0.19.1
  .github/workflows/kind.yml
  common/scripts/ibm_licensing_operator_install.sh
Labels: approved, lgtm, size/S

#833 Add explicit login to the artifactory
  .github/workflows/kind.yml
Labels: approved, size/XS, lgtm

#834 Add explicit login to the artifactory step in kind workflow
  .github/workflows/kind.yml
Labels: approved, size/XS

#832 Olm version update to v0.19.1 (#824)
  .github/workflows/kind.yml
  common/scripts/ibm_licensing_operator_install.sh
Labels: approved, lgtm, size/S

#831 Update operator-framework/api to v0.17.7
  go.mod
  go.sum
Labels: approved, size/L

#835 License check in tests
  controllers/ibmlicensing_controller_test.go
Labels: approved, lgtm, size/M

#836 Upgrade operator-framework/api to version v0.5.0 (/x/text/ v0.3.4)
  go.mod
  go.sum
Labels: approved, size/M

#838 Update to version 1.20.8
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/relatedImages.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: approved, size/M

#839 rename lsr token secret
  api/v1alpha1/helper.go
Labels: approved, size/XS, lgtm

#840 Add check for the nil Spec - avoid nullpointer
  controllers/ibmlicensing_controller_test.go
Labels: approved, size/XS

#841 update remaining CRD descriptions
  api/v1/ibmlicensingdefinition_types.go
  api/v1/ibmlicensingquerysource_types.go
  api/v1alpha1/ibmlicensing_types.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensingdefinitions.yaml
  bundle/manifests/operator.ibm.com_ibmlicensingquerysources.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  config/crd/bases/operator.ibm.com_ibmlicensingdefinitions.yaml
  config/crd/bases/operator.ibm.com_ibmlicensingquerysources.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#844 Update to version 4.2.1
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/relatedImages.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: approved, size/M

#845 Upgrade go to 1.20.6, force upgrade prometheus/client_golang to v1.11.1
  .github/workflows/ci.yml
  .github/workflows/kind.yml
  api/v1alpha1/helper.go
  controllers/ibmlicenseservicereporter_controller.go
  controllers/ibmlicensing_controller.go
  controllers/resources/helper.go
  controllers/resources/reporter/services.go
  controllers/resources/service/meter_definition.go
  controllers/resources/service/services.go
  go.mod
  go.sum
Labels: approved, lgtm, size/XXL
