Repository IBM/ibm-licensing-operator, pull requests merged in 2023-08, with the labels that each got.

#822 Enable certificate generation when ingress is enabled
  controllers/ibmlicensing_controller.go
Labels: approved, size/S

#821 Update to version 4.2.0
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/relatedImages.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: approved, size/M

#820 License acceptance - increment #2
  api/v1alpha1/license.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/ibmlicensing_controller.go
  controllers/suite_test.go
  main.go
Labels: approved, size/M

#826 capture the error from make unit-test
  .github/workflows/kind.yml
  .gitignore
Labels: approved, size/XS

#827 Add checking exit code check in pipeline
  .github/workflows/kind.yml
  .gitignore
Labels: approved, size/XS

#829 fixes for links
  Makefile
  bundle.Dockerfile
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/S
