Repository IBM/ibm-licensing-operator, pull requests merged in 2023-04, with the labels that each got.

#775 do not add redundant namespaces to operatorgroup
  controllers/operandrequest_discovery.go
Labels: approved, size/XS, lgtm

#782 Update to version 1.20.3
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/relatedImages.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: approved, size/M

#778 Update default channels cd
  Makefile
Labels: size/S

#777 Update default channels
  Makefile
Labels: size/S

#783 improve searchability
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#787 migrate prow to aws
  common/Makefile.common.mk
Labels: approved, size/XS, lgtm

#788 migrate prow to aws (ltsr)
  common/Makefile.common.mk
Labels: approved, size/XS, lgtm

#779 Handle Cloud Pak 2.0 and 3.0 coexistence scenario (cs-control namespace)
  .github/workflows/kind.yml
  bundle.Dockerfile
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/ibmlicensing_controller_test.go
  controllers/operandrequest_controller.go
  controllers/operandrequest_controller_test.go
  controllers/resources/envs.go
  controllers/resources/envs_test.go
  controllers/resources/namespacescopes.go
  controllers/resources/operandbindinfos.go
  controllers/resources/operandbindinfos_test.go
  controllers/resources/testutil.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, size/XL

#785 adjust default resources
  api/v1alpha1/helper.go
Labels: approved, size/XS, lgtm

#786 adjust default resources
  api/v1alpha1/helper.go
Labels: approved, size/XS, lgtm

#791 remove operandbindinfo and request from alm.example
  Makefile
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensingbindinfo.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensingrequest.yaml
Labels: approved, lgtm, size/M

#792 Change default crd reconcile interval
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, size/XS, lgtm

#793 Trigger build with new go version
  README.md
Labels: approved, size/XS, lgtm
