Repository IBM/ibm-licensing-operator, pull requests merged in 2023-10, with the labels that each got.

#846 60234 updates
  README.md
Labels: size/S, needs-ok-to-test

#848 Update to version 1.20.9
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/relatedImages.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: approved, size/M

#849 Remediate CVEs by upgrading golang.org/x/net package to v0.17.0 and g…
  .github/workflows/ci.yml
  .github/workflows/kind.yml
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#850 Remediate CVEs by upgrading golang.org/x/net package to v0.17.0 and g…
  .github/workflows/ci.yml
  .github/workflows/kind.yml
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#854 Change operands used in catalog to integration
  Makefile
Labels: approved, lgtm, size/S

#853 Change operands used in catalog to integration
  Makefile
Labels: approved, size/XS, lgtm

#851 [LTSR] fix operator not reconciling reporter upload token secret name for LS
  controllers/resources/deployments.go
  controllers/resources/deployments_test.go
  testutils/mocks.go
Labels: approved, lgtm, size/L

#852 fix operator not reconciling reporter upload token secret name for LS
  controllers/resources/deployments.go
  controllers/resources/deployments_test.go
  testutils/mocks.go
Labels: approved, lgtm, size/L

#855 Add ephemeral storage request and emptyDir size limit
  Makefile
  api/v1alpha1/helper.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/resources/deployments.go
  controllers/resources/service/volumes.go
Labels: approved, lgtm, size/S

#830 Add new aggregation policy: ADD_MONTHLY
  api/v1/ibmlicensingquerysource_types.go
  bundle/manifests/operator.ibm.com_ibmlicensingquerysources.yaml
  config/crd/bases/operator.ibm.com_ibmlicensingquerysources.yaml
Labels: approved, size/XS

#858 Change volumes comparison function to order-agnostic
  controllers/resources/deployments.go
  controllers/resources/deployments_test.go
  testutils/mocks.go
Labels: approved, lgtm, size/L

#859 Revert "Add ephemeral storage request and emptyDir size limit"
  Makefile
  api/v1alpha1/helper.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/resources/deployments.go
  controllers/resources/service/volumes.go
Labels: approved, lgtm, size/S
