Repository IBM/ibm-licensing-operator, pull requests merged in 2023-05, with the labels that each got.

#796 Update to version 1.20.4
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/relatedImages.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: approved, lgtm, size/M

#789 add spec.license.accept field to IBMLicensing CR
  api/v1alpha1/ibmlicensing_types.go
  api/v1alpha1/license.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  controllers/ibmlicensing_controller.go
  controllers/ibmlicensing_controller_test.go
Labels: approved, lgtm, size/L

#798 change License Service license description
  api/v1alpha1/ibmlicensing_types.go
  api/v1alpha1/license.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  controllers/ibmlicensing_controller.go
Labels: approved, lgtm, size/M

#799 update-golang-version
  .github/workflows/ci.yml
Labels: approved, size/XS, lgtm

#800 lmatyasik
  controllers/resources/service/service_monitor.go
Labels: approved, lgtm, size/S
