Repository IBM/ibm-licensing-operator, pull requests merged in 2023-06, with the labels that each got.

#802 Update to version 1.20.5
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/relatedImages.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: lgtm, size/M

#804 Update go to 1.20.5 ltsr
  .github/workflows/ci.yml
  .github/workflows/kind.yml
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#803 Bump go to version 1.20.5
  .github/workflows/ci.yml
  .github/workflows/kind.yml
Labels: approved, size/S

#806 Update to version 4.1.0
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/relatedImages.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: lgtm, size/M

#809 Image pull policy ltsr
  Makefile
  api/v1alpha1/features/zz_generated.deepcopy.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicenseservicereporters.yaml
  bundle/manifests/operator.ibm.com_ibmlicensingdefinitions.yaml
  bundle/manifests/operator.ibm.com_ibmlicensingmetadatas.yaml
  bundle/manifests/operator.ibm.com_ibmlicensingquerysources.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_ibmlicenseservicereporters.yaml
  config/crd/bases/operator.ibm.com_ibmlicensingdefinitions.yaml
  config/crd/bases/operator.ibm.com_ibmlicensingmetadatas.yaml
  config/crd/bases/operator.ibm.com_ibmlicensingquerysources.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
Labels: approved, lgtm, size/XL

#808 Image pull policy
  Makefile
  bundle.Dockerfile
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/manager.yaml
Labels: approved, lgtm, size/S

#810 CVE-2022-3172 Medium k8s.io/Apimachinery-v0.25.0
  go.mod
Labels: approved, size/XS, lgtm
