Repository IBM/ibm-licensing-operator, pull requests merged in 2023-11, with the labels that each got.

#857 Add spec labels support
  api/v1alpha1/ibmlicensing_types.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  controllers/ibmlicensing_controller.go
  controllers/resources/deployments.go
  controllers/resources/helper.go
  controllers/resources/service/helper.go
  controllers/resources/service/secrets.go
  controllers/resources/service/service_monitor.go
  controllers/resources/service/services.go
Labels: approved, lgtm, size/L

#860 Use apimachinery DeepEqual for Volumes comparison
  Makefile
  api/v1alpha1/helper.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/resources/deployments.go
  controllers/resources/service/volumes.go
Labels: approved, lgtm, size/M

#863 Update to version 1.20.10
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/relatedImages.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicenseservicereporter.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: approved, size/M

#867 Update to version 4.2.2
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/relatedImages.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: approved, lgtm, size/M

#869 restrict RBAC permissions
  bundle.Dockerfile
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicenseservicereporters.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_ibmlicenseservicereporters.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  config/rbac/role.yaml
  controllers/ibmlicenseservicereporter_controller.go
  controllers/ibmlicensing_controller.go
Labels: approved, lgtm, size/L

#868 Remove spec.labels support for prometheus cert
  controllers/ibmlicensing_controller.go
Labels: approved, lgtm, size/S
