Repository IBM/ibm-licensing-operator, pull requests merged in 2024-05, with the labels that each got.

#901 Fix CVE 2024 24786 cd
  go.mod
  go.sum
Labels: approved, size/XS

#902 Fix CVE-2024-24786 by upgrading protobuf to v1.33
  go.mod
  go.sum
Labels: approved, size/XS

#900 Fix bug 62463
  bundle/manifests/ibm-license-service-cluster-monitoring-view_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/Makefile.common.mk
  common/config/.golangci.yml
  config/rbac/role_binding.yaml
Labels: approved, size/M

#904 [LTSR] Fix bug 63327
  bundle/manifests/ibm-license-service-cluster-monitoring-view_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/Makefile.common.mk
  config/rbac/role_binding.yaml
Labels: approved, lgtm, size/M

#909 Added custom annotations
  api/v1alpha1/ibmlicensing_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  controllers/ibmlicensing_controller.go
  controllers/resources/helper.go
  controllers/resources/service/deployments.go
  controllers/resources/service/helper_test.go
  controllers/resources/service/secrets.go
  controllers/resources/service/service_monitor.go
  controllers/resources/service/services.go
Labels: approved, lgtm, size/L

#908 Upgrade operator-sdk and controller-gen versions
  Makefile
  api/v1/zz_generated.deepcopy.go
  api/v1alpha1/features/zz_generated.deepcopy.go
  api/v1alpha1/ibmlicensing_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensingdefinitions.yaml
  bundle/manifests/operator.ibm.com_ibmlicensingmetadatas.yaml
  bundle/manifests/operator.ibm.com_ibmlicensingquerysources.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_ibmlicensingdefinitions.yaml
  config/crd/bases/operator.ibm.com_ibmlicensingmetadatas.yaml
  config/crd/bases/operator.ibm.com_ibmlicensingquerysources.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  config/rbac/role.yaml
  controllers/ibmlicensing_controller.go
  controllers/resources/helper.go
  controllers/resources/service/deployments.go
  controllers/resources/service/helper_test.go
  controllers/resources/service/secrets.go
  controllers/resources/service/service_monitor.go
  controllers/resources/service/services.go
Labels: approved, lgtm, size/XXL

#907 [LTSR] Reconcile on imagePullSecrets change in IBMLicensing CR
  controllers/resources/deployments.go
  controllers/resources/service/deployments.go
Labels: approved, size/S

#914 Update to version 4.2.5
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/relatedImages.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: approved, size/M

#910 Release 4.7 features
  Makefile
  api/v1/zz_generated.deepcopy.go
  api/v1alpha1/features/zz_generated.deepcopy.go
  api/v1alpha1/ibmlicensing_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensingdefinitions.yaml
  bundle/manifests/operator.ibm.com_ibmlicensingmetadatas.yaml
  bundle/manifests/operator.ibm.com_ibmlicensingquerysources.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_ibmlicensingdefinitions.yaml
  config/crd/bases/operator.ibm.com_ibmlicensingmetadatas.yaml
  config/crd/bases/operator.ibm.com_ibmlicensingquerysources.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  config/rbac/role.yaml
  controllers/ibmlicensing_controller.go
  controllers/resources/deployments.go
  controllers/resources/helper.go
  controllers/resources/service/deployments.go
  controllers/resources/service/helper_test.go
  controllers/resources/service/secrets.go
  controllers/resources/service/service_monitor.go
  controllers/resources/service/services.go
Labels: approved, lgtm, size/XXL
