Repository IBM/ibm-licensing-operator, pull requests merged in 2024-12, with the labels that each got.

#948 ILS-249 Add remove field to IBMLicensingDefinition
  api/v1/ibmlicensingdefinition_types.go
  api/v1/zz_generated.deepcopy.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensingdefinitions.yaml
  config/crd/bases/operator.ibm.com_ibmlicensingdefinitions.yaml
Labels: approved, lgtm, size/S

#956 Update to version 4.2.12
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/relatedImages.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: approved, size/M

#951 ILS-240 update YAML file for offline LSR install mode
  deploy/yamls/license-service-reporter/install/install-license-service-reporter-no-olm-offline.yaml
Labels: approved, size/S

#957 Release future - merge after version upgrade
  .github/workflows/ci.yml
  api/v1/ibmlicensingdefinition_types.go
  api/v1/zz_generated.deepcopy.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensingdefinitions.yaml
  common/config/.golangci.yml
  config/crd/bases/operator.ibm.com_ibmlicensingdefinitions.yaml
  controllers/ibmlicensing_controller.go
Labels: approved, size/M

#959 Ils 317 bump golang version, FIX CVE-2024-24790
  go.mod
  go.sum
Labels: approved, size/XS, lgtm

#960 Updated crypto to 0.31.0
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#961 Add missing deployment metadata
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, lgtm, size/S

#962 ILS-338 Upgrade golang/x/net package to unaffceted version 0.33.0
  go.mod
  go.sum
Labels: size/XS
