Repository IBM/ibm-licensing-operator, pull requests merged in 2024-09, with the labels that each got.

#933 Update to version 4.2.9
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/relatedImages.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: approved, size/M

#930 Extend operand permissions
  .github/workflows/kind.yml
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/rbac/role_operands.yaml
Labels: approved, lgtm, size/M

#929 Fix 64528 add security context
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/resources/containers.go
Labels: approved, size/XS, lgtm

#935 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/S

#936 Add generated files for roles
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: approved, lgtm, size/S

#937 change name of artifact
  .github/workflows/kind.yml
Labels: approved, size/XS, lgtm
