Repository IBM/ibm-licensing-operator, pull requests merged in 2024-01, with the labels that each got.

#870 restrict RBAC permissions
  api/v1alpha1/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/rbac/role.yaml
  controllers/ibmlicensing_controller.go
  controllers/operandrequest_controller.go
  controllers/operandrequest_discovery.go
Labels: approved, lgtm, size/L

#879 Harden docker security cd
  bundle.Dockerfile
  common/scripts/catalog/Dockerfile
  common/scripts/catalog_build.sh
Labels: approved, size/XS

#878 Add USER instruction to the dockerfiles to enhance security
  bundle.Dockerfile
  common/scripts/catalog/Dockerfile
  common/scripts/catalog_build.sh
Labels: approved, size/XS

#883 Unify getting TLSConfig for RHMOP and alerting service monitors
  controllers/resources/service/service_monitor.go
Labels: approved, lgtm, size/S

#881 Replace HUB_TOKEN env with mounted volume in the LS operand container
  api/v1alpha1/helper.go
  api/v1alpha1/ibmlicensing_types.go
  bundle.Dockerfile
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  controllers/resources/service/containers.go
  controllers/resources/service/secrets.go
  controllers/resources/service/volumes.go
  controllers/resources/service/volumes_test.go
  go.mod
  go.sum
Labels: approved, size/L

#885 Revert LSR Secret rename
  api/v1alpha1/helper.go
  api/v1alpha1/ibmlicensing_types.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  controllers/resources/service/secrets.go
  controllers/resources/service/volumes.go
  controllers/resources/service/volumes_test.go
Labels: approved, lgtm, size/S

#887 Update to version 4.2.3
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/relatedImages.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: approved, size/M

#872 Fix labels auto removal
  controllers/ibmlicensing_controller.go
  controllers/operandrequest_controller.go
  controllers/resources/deployments.go
  controllers/resources/helper.go
  controllers/resources/service/helper_test.go
  go.mod
Labels: approved, lgtm, size/L
