Repository IBM/ibm-licensing-operator, pull requests merged in 2024-10, with the labels that each got.

#938 ILS-175 Update 4.2.10
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/relatedImages.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: approved, size/M

#939 Add opreq status
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/operandrequest_controller.go
Labels: approved, lgtm, size/M

#940 Reporting Interval as property in CustomResourceDefinition
  api/v1alpha1/ibmlicensing_types.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  controllers/resources/service/containers.go
Labels: approved, lgtm, size/M

#944 Ils 206 hide cr field
  api/v1alpha1/ibmlicensing_types.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
Labels: approved, lgtm, size/S

#943 implement Instana metrics collection integration
  api/v1alpha1/ibmlicensing_types.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  controllers/resources/service/containers.go
Labels: approved, lgtm, size/S
