Repository IBM/ibm-licensing-operator, pull requests merged in 2024-11, with the labels that each got.

#945 ILS-233 LS operator keeps restarting when there is OperandRequest in non-existent namespace
  controllers/operandrequest_discovery.go
Labels: approved, lgtm, size/S

#947 Update to version 4.2.11
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/relatedImages.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: approved, size/M

#949 ILS-240 provide distinct YAML files for offline and online mode
  deploy/yamls/license-service-reporter/install/install-license-service-reporter-no-olm-offline.yaml
  deploy/yamls/license-service-reporter/install/install-license-service-reporter-no-olm.yaml
Labels: approved, size/XXL

#946 ILS-233 Add additional check to prevent adding terminating namespace to OperatorGroup
  controllers/operandrequest_discovery.go
  controllers/operatorgroup_cleaner.go
Labels: approved, size/M
