Repository IBM/ibm-licensing-operator, pull requests merged in 2024-06, with the labels that each got.

#912 Add sender certificates secret volume configuration
  api/v1alpha1/ibmlicensing_types.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  controllers/resources/service/containers.go
  controllers/resources/service/containers_test.go
  controllers/resources/service/volumes.go
  controllers/resources/service/volumes_test.go
Labels: approved, size/L

#920 Update to version 4.2.6
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/relatedImages.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: approved, size/M

#915 [LTSR] Added ingress class name option to avoid using deprecated annotations
  api/v1alpha1/ibmlicensing_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  controllers/resources/service/routing.go
Labels: approved, lgtm, size/M

#913 Added ingress class name option to avoid using deprecated annotation
  README.md
  api/v1alpha1/ibmlicensing_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  controllers/resources/service/routing.go
Labels: approved, lgtm, size/M

#918 Switch from reflect.DeepEqual to Semantic.DeepEqual
  controllers/ibmlicenseservicereporter_controller.go
  controllers/ibmlicensing_controller.go
  controllers/resources/deployments.go
  controllers/resources/helper.go
  controllers/resources/reporter/helper.go
Labels: approved, lgtm, size/M

#917 Change reflect.DeepEqual to Semantic.DeepEqual()
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  controllers/ibmlicensing_controller.go
  controllers/resources/deployments.go
  controllers/resources/helper.go
  controllers/resources/operatorgroups_test.go
Labels: approved, lgtm, size/M

#916 remove usege-based container from controller
  Makefile
  api/v1alpha1/helper.go
  api/v1alpha1/ibmlicensing_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  common/relatedImages.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  controllers/ibmlicensing_controller.go
  controllers/ibmlicensing_controller_test.go
  controllers/resources/service/containers.go
  controllers/resources/service/helper.go
  controllers/resources/service/services.go
Labels: approved, lgtm, size/L

#919 Remove usageBased container from LTSR operator
  Makefile
  api/v1alpha1/helper.go
  api/v1alpha1/ibmlicensing_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  common/relatedImages.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  controllers/ibmlicensing_controller.go
  controllers/ibmlicensing_controller_test.go
  controllers/resources/service/containers.go
  controllers/resources/service/helper.go
  controllers/resources/service/services.go
  deploy-old/operator.yaml
Labels: approved, lgtm, size/L

#921 Port SSL validation when sending data from LS do LSR
  api/v1alpha1/helper.go
  api/v1alpha1/ibmlicensing_types.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  controllers/ibmlicenseservicereporter_controller.go
  controllers/resources/reporter/helper.go
  controllers/resources/service/containers.go
  controllers/resources/service/containers_test.go
  controllers/resources/service/volumes.go
  controllers/resources/service/volumes_test.go
  go.mod
  go.sum
Labels: approved, size/L
