Repository IBM/ibm-licensing-operator, pull requests merged in 2024-03, with the labels that each got.

#893 Added optional field to Reporter CRD
  api/v1alpha1/ibmlicenseservicereporter_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/operator.ibm.com_ibmlicenseservicereporters.yaml
  config/crd/bases/operator.ibm.com_ibmlicenseservicereporters.yaml
Labels: approved, lgtm, size/XXL

#892 Add option to limit LS ns visibility without OLM
  api/v1alpha1/features.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  common/config/.golangci.yml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  controllers/resources/operatorgroups.go
  controllers/resources/service/containers.go
Labels: approved, lgtm, size/M

#894 enable hugepages resources requests/limits support
  api/v1alpha1/helper.go
  controllers/resources/deployments.go
  controllers/resources/deployments_test.go
Labels: approved, lgtm, size/L
