Repository IBM/ibm-licensing-operator, pull requests merged in 2024-07, with the labels that each got.

#924 Update to version 4.2.7
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/relatedImages.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  version/version.go
Labels: approved, size/M

#922 Add param for reporting limited namespace scoping feature
  api/v1alpha1/features.go
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_ibmlicensings.yaml
  config/crd/bases/operator.ibm.com_ibmlicensings.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  controllers/resources/service/containers.go
  controllers/resources/service/containers_test.go
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#923 Use ubi9-minimal base image from internal registry
  Dockerfile
Labels: approved, size/XS
