Repository IBM/ibm-licensing-operator, pull requests merged in 2025-01, with the labels that each got.

#965 Added generation of yaml files for argo-cd
  Makefile
Labels: approved, lgtm, size/M

#950 Add ArgoCD support for Licensing
  common/scripts/next_csv.sh
  deploy/argo-cd/README.md
  deploy/argo-cd/applications/license-service.yaml
  deploy/argo-cd/applications/reporter.yaml
  deploy/argo-cd/applications/scanner.yaml
  deploy/argo-cd/components/license-service/Chart.yaml
  deploy/argo-cd/components/license-service/templates/cluster-rbac.yaml
  deploy/argo-cd/components/license-service/templates/cr.yaml
  deploy/argo-cd/components/license-service/templates/crds.yaml
  deploy/argo-cd/components/license-service/templates/deployment.yaml
  deploy/argo-cd/components/license-service/templates/rbac.yaml
  deploy/argo-cd/components/license-service/templates/serviceaccounts.yaml
  deploy/argo-cd/components/reporter/Chart.yaml
  deploy/argo-cd/components/reporter/templates/cluster-rbac.yaml
  deploy/argo-cd/components/reporter/templates/cr.yaml
  deploy/argo-cd/components/reporter/templates/crd.yaml
  deploy/argo-cd/components/reporter/templates/deployment.yaml
  deploy/argo-cd/components/reporter/templates/rbac.yaml
  deploy/argo-cd/components/reporter/templates/serviceaccounts.yaml
  deploy/argo-cd/components/scanner/Chart.yaml
  deploy/argo-cd/components/scanner/templates/cluster-rbac.yaml
  deploy/argo-cd/components/scanner/templates/cr.yaml
  deploy/argo-cd/components/scanner/templates/crd.yaml
  deploy/argo-cd/components/scanner/templates/deployment.yaml
  deploy/argo-cd/components/scanner/templates/rbac-for-auto-connect.yaml
  deploy/argo-cd/components/scanner/templates/rbac.yaml
  deploy/argo-cd/components/scanner/templates/serviceaccounts.yaml
  deploy/argo-cd/docs/images/applications-screen.png
  deploy/argo-cd/docs/images/argo-cd-ui-step-1.png
  deploy/argo-cd/docs/images/argo-cd-ui-step-2.png
  deploy/argo-cd/docs/images/components.png
  deploy/argo-cd/docs/images/install-red-hat-openshift-gitops-step-1.png
  deploy/argo-cd/docs/images/install-red-hat-openshift-gitops-step-2.png
  deploy/argo-cd/prerequisites/cluster-rbac-for-argocd.yaml
  deploy/argo-cd/prerequisites/licensing/cluster-rbac-for-argocd.yaml
  deploy/argo-cd/prerequisites/licensing/namespace.yaml
  deploy/argo-cd/prerequisites/licensing/rbac-for-argocd.yaml
  deploy/argo-cd/prerequisites/reporter/namespace.yaml
  deploy/argo-cd/prerequisites/reporter/rbac-for-argocd.yaml
  deploy/argo-cd/prerequisites/scanner/namespace.yaml
  deploy/argo-cd/prerequisites/scanner/operand-request-crd.yaml
  deploy/argo-cd/prerequisites/scanner/rbac-for-argocd.yaml
Labels: approved, lgtm, size/XXL

#970 ILS-390 Add required OLM operator bundle metadata
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#966 [skip ci] Add helm install support
  deploy/argo-cd/README.md
  deploy/argo-cd/applications/license-service.yaml
  deploy/argo-cd/applications/reporter.yaml
  deploy/argo-cd/applications/scanner.yaml
  deploy/argo-cd/components/license-service/helm-cluster-scoped/Chart.yaml
  deploy/argo-cd/components/license-service/helm-cluster-scoped/templates/cluster-rbac.yaml
  deploy/argo-cd/components/license-service/helm-cluster-scoped/templates/crds.yaml
  deploy/argo-cd/components/license-service/helm-cluster-scoped/values.yaml
  deploy/argo-cd/components/license-service/helm/Chart.yaml
  deploy/argo-cd/components/license-service/helm/templates/cr.yaml
  deploy/argo-cd/components/license-service/helm/templates/deployment.yaml
  deploy/argo-cd/components/license-service/helm/templates/rbac.yaml
  deploy/argo-cd/components/license-service/helm/templates/serviceaccounts.yaml
  deploy/argo-cd/components/license-service/helm/values.yaml
  deploy/argo-cd/components/license-service/templates/cr.yaml
  deploy/argo-cd/components/reporter/helm-cluster-scoped/Chart.yaml
  deploy/argo-cd/components/reporter/helm-cluster-scoped/templates/cluster-rbac.yaml
  deploy/argo-cd/components/reporter/helm-cluster-scoped/templates/crd.yaml
  deploy/argo-cd/components/reporter/helm-cluster-scoped/values.yaml
  deploy/argo-cd/components/reporter/helm/Chart.yaml
  deploy/argo-cd/components/reporter/helm/templates/cr.yaml
  deploy/argo-cd/components/reporter/helm/templates/deployment.yaml
  deploy/argo-cd/components/reporter/helm/templates/rbac.yaml
  deploy/argo-cd/components/reporter/helm/templates/serviceaccounts.yaml
  deploy/argo-cd/components/reporter/helm/values.yaml
  deploy/argo-cd/components/reporter/templates/cr.yaml
  deploy/argo-cd/components/scanner/helm-cluster-scoped/Chart.yaml
  deploy/argo-cd/components/scanner/helm-cluster-scoped/templates/cluster-rbac.yaml
  deploy/argo-cd/components/scanner/helm-cluster-scoped/templates/crd.yaml
  deploy/argo-cd/components/scanner/helm-cluster-scoped/values.yaml
  deploy/argo-cd/components/scanner/helm/Chart.yaml
  deploy/argo-cd/components/scanner/helm/templates/cr.yaml
  deploy/argo-cd/components/scanner/helm/templates/deployment.yaml
  deploy/argo-cd/components/scanner/helm/templates/rbac-for-auto-connect.yaml
  deploy/argo-cd/components/scanner/helm/templates/rbac.yaml
  deploy/argo-cd/components/scanner/helm/templates/serviceaccounts.yaml
  deploy/argo-cd/components/scanner/helm/values.yaml
  deploy/argo-cd/components/scanner/templates/cr.yaml
Labels: approved, lgtm, size/L
