Repository IBM/ibm-licensing-operator, pull requests merged in 2025-03, with the labels that each got.

#978 Update to version 4.2.14
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/relatedImages.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  deploy/argo-cd/README.md
  deploy/argo-cd/components/license-service/helm-cluster-scoped/Chart.yaml
  deploy/argo-cd/components/license-service/helm/Chart.yaml
  deploy/argo-cd/components/license-service/helm/templates/deployment.yaml
  deploy/argo-cd/components/license-service/helm/values.yaml
  deploy/argo-cd/components/reporter/helm-cluster-scoped/Chart.yaml
  deploy/argo-cd/components/reporter/helm/Chart.yaml
  deploy/argo-cd/components/reporter/helm/templates/deployment.yaml
  deploy/argo-cd/components/reporter/helm/values.yaml
  deploy/argo-cd/components/scanner/helm-cluster-scoped/Chart.yaml
  deploy/argo-cd/components/scanner/helm/Chart.yaml
  deploy/argo-cd/components/scanner/helm/templates/deployment.yaml
  version/version.go
Labels: size/M

#979 ILS-580 Remediate CVE 2025 22870
  .github/workflows/ci.yml
  .github/workflows/kind.yml
Labels: size/XS

#980 Ils 579 CVE 2025 22869
  go.mod
  go.sum
Labels: size/S

#983 Add relevant helm template support to ibm-licensing-operator
  deploy/argo-cd/README.md
  deploy/argo-cd/components/license-service/helm/templates/cr.yaml
  deploy/argo-cd/components/license-service/helm/templates/deployment.yaml
  deploy/argo-cd/components/license-service/helm/values.yaml
  deploy/argo-cd/components/reporter/helm/templates/cr.yaml
  deploy/argo-cd/components/reporter/helm/templates/deployment.yaml
  deploy/argo-cd/components/reporter/helm/values.yaml
  deploy/argo-cd/components/scanner/helm/templates/cr.yaml
  deploy/argo-cd/components/scanner/helm/templates/deployment.yaml
  deploy/argo-cd/components/scanner/helm/values.yaml
Labels: approved, lgtm, size/L

#984 Remediate CVE-2025-22870 - golang.org/x/net
  Makefile
  go.mod
  go.sum
Labels: size/XS

#982 ILS-584
  .github/workflows/ci.yml
  .github/workflows/kind.yml
Labels: approved, size/XS
