Repository IBM/ibm-licensing-operator, pull requests merged in 2025-02, with the labels that each got.

#972 Update to version 4.2.13
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/relatedImages.yaml
  common/scripts/next_csv.sh
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  deploy/argo-cd/README.md
  deploy/argo-cd/components/license-service/helm-cluster-scoped/Chart.yaml
  deploy/argo-cd/components/license-service/helm/Chart.yaml
  deploy/argo-cd/components/license-service/helm/templates/deployment.yaml
  deploy/argo-cd/components/license-service/helm/values.yaml
  deploy/argo-cd/components/reporter/helm-cluster-scoped/Chart.yaml
  deploy/argo-cd/components/reporter/helm/Chart.yaml
  deploy/argo-cd/components/reporter/helm/templates/deployment.yaml
  deploy/argo-cd/components/reporter/helm/values.yaml
  deploy/argo-cd/components/scanner/helm-cluster-scoped/Chart.yaml
  deploy/argo-cd/components/scanner/helm/Chart.yaml
  deploy/argo-cd/components/scanner/helm/templates/deployment.yaml
  deploy/argo-cd/prerequisites/scanner/namespace.yaml
  version/version.go
Labels: size/M

#973 ILS-461 Fix operator scans issues
  Makefile
  bundle.Dockerfile
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#974 ILS-461 Fix operator scans issues
  Makefile
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
Labels: approved, size/XS, lgtm
