Repository IBM/ibm-licensing-operator, pull requests merged in 2025-04, with the labels that each got.

#985 Update 4.2.15
  Makefile
  README.md
  bundle/manifests/ibm-licensing-operator.clusterserviceversion.yaml
  common/relatedImages.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-licensing-operator.clusterserviceversion.yaml
  config/samples/operator.ibm.com_v1alpha1_ibmlicensing.yaml
  deploy/argo-cd/README.md
  deploy/argo-cd/components/license-service/helm-cluster-scoped/Chart.yaml
  deploy/argo-cd/components/license-service/helm/Chart.yaml
  deploy/argo-cd/components/license-service/helm/templates/deployment.yaml
  deploy/argo-cd/components/license-service/helm/values.yaml
  deploy/argo-cd/components/reporter/helm-cluster-scoped/Chart.yaml
  deploy/argo-cd/components/reporter/helm/Chart.yaml
  deploy/argo-cd/components/reporter/helm/templates/deployment.yaml
  deploy/argo-cd/components/reporter/helm/values.yaml
  deploy/argo-cd/components/scanner/helm-cluster-scoped/Chart.yaml
  deploy/argo-cd/components/scanner/helm/Chart.yaml
  deploy/argo-cd/components/scanner/helm/templates/deployment.yaml
  version/version.go
Labels: size/M

#986 Add changes for licensing deploy info
  Makefile
  common/makefile-generate/yaml-cr-spec-part
  common/makefile-generate/yaml-deployment-pull-secrets-part
Labels: approved, lgtm, size/S

#988 Upgrade /x/net to v0.38.0
  go.mod
  go.sum
Labels: size/M

#989 Update no olm yamls
  deploy/yamls/license-service-reporter/install/install-license-service-reporter-no-olm-offline.yaml
  deploy/yamls/license-service-reporter/install/install-license-service-reporter-no-olm.yaml
Labels: approved, size/M
